#include "WCPNav/ExampleGDS.h"
#include "WCPNav/GenerativeFDS.h"
#include "WCPNav/PepperDepositor.h"
#include "WCPNav/SliceDataSource.h"

#include "WCP2dToy/ToyTiling.h"

#include "WCPData/Units.h"
#include "WCPData/Slice.h"

#include <iostream>
#include <string>

using namespace std;
using namespace WCP;


template<typename OK>
/**
 * @brief Asserts that the given condition is true, exiting with error message if false
 * @param ok the condition to check
 * @param msg the error message to display on failure
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
void assert(const OK& ok, string msg="error")
{
    if (ok) { return; }
    cerr << msg << endl;
    exit(-1);
}


/**
 * Main program entry point
 *
 * Initializes simulation parameters and runs the simulation
  
 * Sets up the simulation environment including depositor and geometry data source
 *
 * @param none
 * @return none
 
 * Creates an instance of the generative finite difference solver
 *
 * @param dep Depositor object containing simulation parameters
 * @param gds Geometry data source object
 * @return none
 
 * Jumps the finite difference solver to the initial state
 *
 * @param index Initial state index
 * @return none
 
 * Creates a slice data source object from the finite difference solver
 *
 * @param fds Finite difference solver object
 * @return none
 
 * Jumps the slice data source to the initial state
 *
 * @param index Initial state index
 * @return none
 
 * Retrieves the current slice from the slice data source
 *
 * @return Current slice object
 
 * Creates a tiling object for the slice
 *
 * @param slice Current slice object
 * @param gds Geometry data source object
 * @return Tiling object pointer
 
 * Retrieves all cells in the tiling
 *
 * @return Vector of cell selections
 
 * Prints the number of cells in the selection
 *
 * @param none
 * @return none
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
int main () {
    using namespace std;
    const float width = 0.5*units::m;
    const PepperDepositor::MinMax drift_dim(0, 2.0*width), trans_dim(-width,width);
    const PepperDepositor::MinMax charge(1,100);
    PepperDepositor dep(drift_dim, trans_dim, trans_dim, charge, 5);
    
    GeomDataSource* gds = make_example_gds(10*units::mm);

    GenerativeFDS fds(dep, *gds);

    fds.jump(0);    
    SliceDataSource sds(fds);
    
    sds.jump(0);

    const Slice& slice = sds.get();
    
    WCP2dToy::ToyTiling *toytiling = new WCP2dToy::ToyTiling(slice,*gds);
    
    GeomCellSelection allcell = toytiling->get_allcell();
    
    cout << allcell.size() << endl;
    
    return 0;
}
