#include "WCPSst/GeomDataSource.h"
#include "WCP2dToy/FrameDataSource.h"
#include "WCP2dToy/ToyEventDisplay.h"
#include "WCP2dToy/ToyTiling.h"

#include "WCPNav/SliceDataSource.h"
#include "TApplication.h"
#include "TStyle.h"
#include "TH1F.h"
#include <iostream>
using namespace WCP;
using namespace std;




/**
 * Main program entry point
 *
 * @param argc Number of command line arguments
 * @param argv Array of command line argument strings
 * @return Program exit status
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
int main(int argc, char* argv[])
{
 

  std::map<int,float> abc;
  abc[1] = 10;
  abc[2] = 20;
  
  cout << abc[3] << endl;
  return 0;
}
