#include "WCPNav/ExampleGDS.h"
#include "WCPNav/GenerativeFDS.h"
#include "WCPNav/PepperDepositor.h"
#include "WCPNav/SliceDataSource.h"

#include "WCP2dToy/ToyTiling.h"

#include "WCPData/Units.h"
#include "WCPData/Slice.h"

#include <iostream>
#include <string>

using namespace std;
using namespace WCP;


template<typename OK>
/**
 * @brief Asserts that the given condition is true, exiting with error message if false
 * @param ok the condition to check
 * @param msg the error message to display on failure
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void assert(const OK& ok, string msg="error")
{
    if (ok) { return; }
    cerr << msg << endl;
    exit(-1);
}


/**
 * Main program entry point
 *
 * Initializes simulation parameters and runs the simulation
  
 * Sets up the simulation environment
 *
 * Creates instances of necessary data sources and simulation objects
 
 * Jumps to the starting point of the simulation
 *
 * Resets the simulation state to the initial conditions
 
 * Retrieves the current slice of data from the simulation
 *
 * Returns a reference to the current slice object
 
 * Creates a new instance of the ToyTiling class
 *
 * Initializes the tiling object with the current slice and geometry data source
 
 * Retrieves all cells from the tiling object
 *
 * Returns a selection of geometry cells
 
 * Prints the size of the cell selection to the console
 *
 * Outputs the number of cells in the selection
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
int main () {
    using namespace std;
    const float width = 0.5*units::m;
    const PepperDepositor::MinMax drift_dim(0, 2.0*width), trans_dim(-width,width);
    const PepperDepositor::MinMax charge(1,100);
    PepperDepositor dep(drift_dim, trans_dim, trans_dim, charge, 5);
    
    GeomDataSource* gds = make_example_gds(10*units::mm);

    GenerativeFDS fds(dep, *gds);

    fds.jump(0);    
    SliceDataSource sds(fds);
    
    sds.jump(0);

    const Slice& slice = sds.get();
    
    WCP2dToy::ToyTiling *toytiling = new WCP2dToy::ToyTiling(slice,*gds);
    
    GeomCellSelection allcell = toytiling->get_allcell();
    
    cout << allcell.size() << endl;
    
    return 0;
}
