#include "WCPNanoflann/nanoflann.h" 
#include "WCPData/WCPointCloud.h"

#include "TRandom.h"

using namespace WCP;

/**
 * @brief Initializes a point cloud with random points
 *
 * Creates a point cloud with 1000 points having random x, y, z coordinates
 * between -100 and 100, and assigns a unique cell identifier to each point
 *
 * @return None
 
for (size_t i = 0; i < 1000; i++)
{
  cloud.pts[i].x = gRandom->Uniform(-100,100);
  cloud.pts[i].y = gRandom->Uniform(-100,100);
  cloud.pts[i].z = gRandom->Uniform(-100,100);
  SlimMergeGeomCell *cell = new SlimMergeGeomCell(i);
  cloud.pts[i].mcell = cell;
}
 * @brief Defines a KD-tree adaptor for efficient nearest neighbor searches
 *
 * Specifies the dimensionality of the data points and the distance metric
 *
 * @tparam dim Dimensionality of the data points
 * @tparam DistanceMetric Distance metric used for nearest neighbor searches
 
typedef nanoflann::KDTreeSingleIndexAdaptor<
  nanoflann::L2_Simple_Adaptor<double, WCPointCloud<double> >,
  WCPointCloud<double>,
  3 /* dim 
> my_kd_tree_t;
 * @brief Builds a KD-tree index for fast nearest neighbor queries
 *
 * Constructs a KD-tree from the point cloud data and builds the index
 *
 * @param dim Dimensionality of the data points
 * @param cloud Point cloud data
 * @param params Parameters for the KD-tree construction
 
my_kd_tree_t   index(3 /*dim, cloud, nanoflann::KDTreeSingleIndexAdaptorParams(10 /* max leaf ));
index.buildIndex();
 * @brief Performs a k-nearest neighbors search
 *
 * Finds the k-nearest neighbors to a query point
 *
 * @param query_pt Query point
 * @param num_results Number of nearest neighbors to find
 * @param ret_index Indices of the nearest neighbors
 * @param out_dist_sqr Squared distances to the nearest neighbors
 * @return Number of nearest neighbors found
 
num_results = index.knnSearch(&query_pt[0], num_results, &ret_index[0], &out_dist_sqr[0]);
 * @brief Prints the results of the k-nearest neighbors search
 *
 * Displays the indices and squared distances of the nearest neighbors
 *
 * @param num_results Number of nearest neighbors found
 * @param ret_index Indices of the nearest neighbors
 * @param out_dist_sqr Squared distances to the nearest neighbors
 
std::cout << "knnSearch(): num_results=" << num_results << "\n";
for (size_t i = 0; i < num_results; i++){
  std::cout << "idx["<< i << "]=" << ret_index[i] << " dist["<< i << "]=" << out_dist_sqr[i] << " " << sqrt(pow(cloud.pts[ret_index[i]].x-0.5,2)+pow(cloud.pts[ret_index[i]].y-0.5,2)+pow(cloud.pts[ret_index[i]].z-0.5,2)) << " " << cloud.pts[ret_index[i]].mcell->GetIdent() << std::endl;
}
std::cout << "\n";
 * @brief Performs a radius search for points within a certain distance
 *
 * Finds all points within a specified radius of a query point
 *
 * @param query_pt Query point
 * @param search_radius Maximum distance for the search
 * @param ret_matches List of points within the search radius
 * @param params Search parameters
 * @return Number of points within the search radius
 
const size_t nMatches = index.radiusSearch(&query_pt[0], search_radius, ret_matches, params);
 * @brief Prints the results of the radius search
 *
 * Displays the indices and distances of the points within the search radius
 *
 * @param search_radius Maximum distance for the search
 * @param nMatches Number of points within the search radius
 * @param ret_matches List of points within the search radius
 
std::cout << "radiusSearch(): radius=" << search_radius << " -> " << nMatches << " matches\n";
for (size_t i = 0; i < nMatches; i++)
  std::cout << "idx["<< i << "]=" << ret_matches[i].first << " dist["<< i << "]=" << ret_matches[i].second << " " << cloud.pts[ret_matches[i].first].mcell->GetIdent()  << std::endl;
std::cout << "\n";* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
int main()
{
  WCPointCloud<double> cloud;
  cloud.pts.resize(1000);
  for (size_t i = 0; i < 1000; i++)
    {
      cloud.pts[i].x = gRandom->Uniform(-100,100);
      cloud.pts[i].y = gRandom->Uniform(-100,100);
      cloud.pts[i].z = gRandom->Uniform(-100,100);
      SlimMergeGeomCell *cell = new SlimMergeGeomCell(i);
      cloud.pts[i].mcell = cell;
    }

  typedef nanoflann::KDTreeSingleIndexAdaptor<
    nanoflann::L2_Simple_Adaptor<double, WCPointCloud<double> > ,
    WCPointCloud<double>,
    3 /* dim */
    > my_kd_tree_t;

  my_kd_tree_t   index(3 /*dim*/, cloud, nanoflann::KDTreeSingleIndexAdaptorParams(10 /* max leaf */) );
  index.buildIndex();

  const double query_pt[3] = { 0.5, 0.5, 0.5};

  {
    size_t num_results = 5;
    std::vector<size_t>   ret_index(num_results);
    std::vector<double>   out_dist_sqr(num_results);
    
    num_results = index.knnSearch(&query_pt[0], num_results, &ret_index[0], &out_dist_sqr[0]);
    
    // In case of less points in the tree than requested:
    ret_index.resize(num_results);
    out_dist_sqr.resize(num_results);
    
    std::cout << "knnSearch(): num_results=" << num_results << "\n";
    for (size_t i = 0; i < num_results; i++){
      // int abc = cloud.pts[ret_index[i]].mcell;
      std::cout << "idx["<< i << "]=" << ret_index[i] << " dist["<< i << "]=" << out_dist_sqr[i] << " " << sqrt(pow(cloud.pts[ret_index[i]].x-0.5,2)+pow(cloud.pts[ret_index[i]].y-0.5,2)+pow(cloud.pts[ret_index[i]].z-0.5,2)) << " " << cloud.pts[ret_index[i]].mcell->GetIdent() << std::endl;
    }
    std::cout << "\n";
    
  }

  // ----------------------------------------------------------------
  // radiusSearch():  Perform a search for the N closest points
  // ----------------------------------------------------------------
  {
  	const double search_radius = 100;
  	std::vector<std::pair<size_t,double> >   ret_matches;
  
  	nanoflann::SearchParams params;
  	//params.sorted = false;
  
  	const size_t nMatches = index.radiusSearch(&query_pt[0], search_radius, ret_matches, params);
  
	std::cout << "radiusSearch(): radius=" << search_radius << " -> " << nMatches << " matches\n";
  	for (size_t i = 0; i < nMatches; i++)
	  std::cout << "idx["<< i << "]=" << ret_matches[i].first << " dist["<< i << "]=" << ret_matches[i].second << " " << cloud.pts[ret_matches[i].first].mcell->GetIdent()  << std::endl;
	std::cout << "\n";
  }

  
  return 0;
}
