#include "WCP2dToy/ToyFiducial.h"

using namespace std;

/**
 * Main program entry point
 *
 * @param argc number of command line arguments
 * @param argv array of command line argument strings
 * @return program exit status
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
int main(int argc, char * argv[]){
  WCP2dToy::ToyFiducial *fid = new WCP2dToy::ToyFiducial();

  WCP::Point p(30.0*units::cm,30*units::cm,30*units::cm);
  WCP::Point p1(110.0*units::cm,0*units::cm,30*units::cm);
  
  std::cout << fid->inside_fiducial_volume(p) << " " << fid->inside_fiducial_volume(p1) << std::endl;;
  
  return 0;
}
