#ifndef WIRECELL2DTOY_CLUSTERDISPLAY_H
#define WIRECELL2DTOY_CLUSTERDISPLAY_H
#include "WCPData/Point.h"
#include "WCPData/SpaceCell.h"
#include "WCPData/MergeSpaceCell.h"

#include "WCP2dToy/ToyCrawler.h"
#include "WCP2dToy/ToyTracking.h"

#include "TPad.h"
#include "TH2F.h"
#include "TString.h"
#include "TGraph.h"
#include "TPolyLine.h"
#include "TString.h"

namespace WCP2dToy {

/**
 * @brief Class representing a cluster display.
 *
 * Provides methods for drawing various elements related to clusters,
 * including cells, merge cells, crawlers, Hough transforms, showers, vertices, and tracks.
 
 
  * @brief Class representing a dynamic toy point cloud.
 *
 * A collection of 3D points in space, used for clustering and reconstruction.
 
 
  * @brief Class representing a PR3D cluster.
 *
 * A group of connected 3D points, potentially forming a track or object.
 
 
  * @brief Class representing a selection of PR3D clusters.
 *
 * A container for holding multiple clusters, allowing for operations such as merging and removal.
 
 
  * @brief Class representing a map of PR3D clusters to doubles.
 *
 * An associative container linking clusters to their corresponding lengths.
 
 
  * @brief Class representing a tuple of three integers.
 *
 * A simple data structure for storing three integer values.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    class ClusterDisplay {
    private:
    
	TPad &pad;
	
    
    public:
	/// Create a ToyEventDisplay drawing into the given TPad using the given GeomDataSource.
	ClusterDisplay(TPad& pad);
	virtual ~ClusterDisplay();
    
	void DrawCluster(WCP::SpaceCellSelection& cells, TString option = "p0");
	void DrawCluster(WCP::MergeSpaceCellSelection& mcells, TString option = "p");
	void DrawCluster(WCP::MergeSpaceCellSelection& mcells, WCP2dToy::ToyTracking& toytracking);

	void DrawCrawler(ToyCrawler& toycrawler, TString option = "p", int flag = 0);
	void DrawHough(WCP::SpaceCellSelection& cells, WCP::Point& p, double dis_near, double dis_far);

	void DrawShower(WCP::WCShower* shower, TString option = "psame", int color = 2); 

	void DrawVertex(WCP::WCVertexSelection& vertices, TString option = "p");
	
	void DrawTracks(WCP::WCTrackSelection& tracks, TString option = "", int color = 1);
    };

}

#endif
