#ifndef WIRECELL2DTOY_MATRIXSOLVER_H
#define WIRECELL2DTOY_MATRIXSOLVER_H

#include "TMatrixD.h"
#include "TVectorD.h"


#include "WCPData/GeomCell.h"
#include "WCPData/GeomWire.h"
#include "WCPData/MergeGeomCell.h"
#include "WCPData/MergeGeomWire.h"


#include <Eigen/Dense>

namespace WCP2dToy{
/**
 * @brief Class representing a matrix solver for wire-cell geometry problems.
 *
 * This class encapsulates the functionality for solving matrix equations related to wire-cell geometry,
 * including direct and L1 solvers. It provides methods for accessing solution parameters and flags.
 *
 * @author [Your Name]
 * @date [Current Date]
 
class MatrixSolver {
  public:
         * @brief Constructor for the MatrixSolver class.
     *
     * Initializes the matrix solver with the given geometric cell and wire selections, maps, and charge maps.
     *
     * @param cells Geometric cell selection.
     * @param wires Geometric wire selection.
     * @param cell_wire_map Map of cells to wires.
     * @param wire_cell_map Map of wires to cells.
     * @param wire_charge_map Map of wire charges.
     * @param wire_charge_error_map Map of wire charge errors.
     
    MatrixSolver(WCP::GeomCellSelection& cells, WCP::GeomWireSelection& wires, WCP::GeomCellMap& cell_wire_map, WCP::GeomWireMap& wire_cell_map, WCP::WireChargeMap& wire_charge_map, WCP::WireChargeMap& wire_charge_error_map);

         * @brief Virtual destructor for the MatrixSolver class.
     
    virtual ~MatrixSolver();

         * @brief Returns the charge of a merged geometric cell.
     *
     * @param mcell Pointer to the merged geometric cell.
     * @return Charge of the merged cell.
     
    double get_mcell_charge(WCP::MergeGeomCell *mcell);

         * @brief Returns the direct chi-squared value.
     *
     * @return Direct chi-squared value.
     
    double get_direct_chi2();

         * @brief Returns the number of degrees of freedom for the direct solver.
     *
     * @return Number of degrees of freedom.
     
    int get_direct_ndf();

         * @brief Returns the L1 chi-squared base value.
     *
     * @return L1 chi-squared base value.
     
    double get_L1_chi2_base();

         * @brief Returns the L1 chi-squared penalty value.
     *
     * @return L1 chi-squared penalty value.
     
    double get_L1_chi2_penalty();

         * @brief Returns the number of degrees of freedom for the L1 solver.
     *
     * @return Number of degrees of freedom.
     
    int get_L1_ndf();

         * @brief Returns the solve flag.
     *
     * @return Solve flag.
     
    int get_solve_flag();

         * @brief Solves the L1 problem using the given cell weight map.
     *
     * @param cell_weight_map Map of cell weights.
     
    void L1_Solve(std::map<const WCP::GeomCell*, double, WCP::GeomCellComparep >& cell_weight_map);

         * @brief Returns all geometric cells.
     *
     * @return Selection of geometric cells.
     
    WCP::GeomCellSelection get_all_cells();

         * @brief Returns the lambda value.
     *
     * @return Lambda value.
     
    double get_lambda();

         * @brief Returns the tolerance value.
     *
     * @return Tolerance value.
     
    double get_TOL();

         * @brief Returns the index of a geometric cell in the matrix.
     *
     * @param cell Pointer to the geometric cell.
     * @return Index of the cell.
     
    int get_mc_index(const WCP::GeomCell* cell);

         * @brief Returns the index of a geometric wire in the matrix.
     *
     * @param wire Pointer to the geometric wire.
     * @return Index of the wire.
     
    int get_mw_index(const WCP::GeomWire* wire);

         * @brief Returns the W value at a given index.
     *
     * @param index Index of the W value.
     * @return W value.
     
    double get_W_value(int index);

         * @brief Returns the G value at given indices.
     *
     * @param index_mw Index of the wire.
     * @param index_mc Index of the cell.
     * @return G value.
     
    double get_G_value(int index_mw, int index_mc);

         * @brief Sets the ID of the matrix solver.
     *
     * @param id1 New ID.
     
    void set_id(int id1);

         * @brief Returns the ID of the matrix solver.
     *
     * @return Current ID.
     
    int get_id();

  private:
    int id;

    int solve_flag;
    double direct_chi2;
    int direct_ndf;

    double L1_chi2_base, L1_chi2_penalty;
    int L1_ndf;

    double lambda;
    double TOL;
    float scale_factor;

    TVectorD *Wy, *Cx, *dCx;
    TVectorD *MWy_pred, *MWy;

    Eigen::VectorXd W;
    Eigen::MatrixXd G;

    WCP::CellIndexMap mcimap;
    WCP::WireIndexMap mwimap, swimap;

    int mcindex;
    int mwindex;
    int swindex;
};* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class MatrixSolver{
  public:
    MatrixSolver(WCP::GeomCellSelection& cells, WCP::GeomWireSelection& wires, WCP::GeomCellMap& cell_wire_map, WCP::GeomWireMap& wire_cell_map, WCP::WireChargeMap& wire_charge_map, WCP::WireChargeMap& wire_charge_error_map);
    virtual ~MatrixSolver();

    double get_mcell_charge(WCP::MergeGeomCell *mcell);

    double get_direct_chi2(){return direct_chi2;};
    int get_direct_ndf(){return direct_ndf;};

    double get_L1_chi2_base(){return L1_chi2_base;};
    double get_L1_chi2_penalty(){return L1_chi2_penalty;};
    int get_L1_ndf(){return L1_ndf;};
    
    int get_solve_flag(){return solve_flag;};

    void L1_Solve(std::map<const WCP::GeomCell*, double, WCP::GeomCellComparep >& cell_weight_map);

    WCP::GeomCellSelection get_all_cells();

    // added to expose more information out ...
    double get_lambda(){return lambda;};
    double get_TOL(){return TOL;};
    int get_mc_index(const WCP::GeomCell* cell);
    int get_mw_index(const WCP::GeomWire* wire);
    double get_W_value(int index);
    double get_G_value(int index_mw, int index_mc);

    void set_id(int id1){id = id1;};
    int get_id(){return id;};
    
  private:
    //    void Direct_Solve();
    int id;
        
    int solve_flag;
    double direct_chi2;
    int direct_ndf;

    double L1_chi2_base, L1_chi2_penalty;
    int L1_ndf;
    
    /* TMatrixD *MA, *MB, *MAT, *MBT; */
    /* TMatrixD *Vy, *VBy, *Vx, *VBy_inv, *Vx_inv; */
    /* TMatrixD *MC, *MC_inv; */

    /* TMatrixD *UMA;  */
    /* TVectorD *UMWy; */ 
    double lambda;
    double TOL;
    float scale_factor;
    
    TVectorD *Wy, *Cx, *dCx;
    TVectorD *MWy_pred, *MWy;

    Eigen::VectorXd W;
    Eigen::MatrixXd G;
    
    WCP::CellIndexMap mcimap;
    WCP::WireIndexMap mwimap, swimap;
    
    
    int mcindex;
    int mwindex;
    int swindex;
    
  };
}

#endif
