// http://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process
// http://stackoverflow.com/questions/669438/how-to-get-memory-usage-at-run-time-in-c

#ifndef WIRECELL_MEMUSAGE
#define WIRECELL_MEMUSAGE

#include <fstream>
#include <vector>
#include <string>


namespace WCP {

    double memusage_resident();
    double memusage_shared();
    double memusage_size();

    
/**
 * Brief description of the class 
 * Detailed description of the class 
   * @class 
 * @brief Class representing memory usage 
 * @details Provides functionality to track and record memory usage events 
 * @author  
 * @version  
 * @date  
   * @var typedef stdpairdouble double memusage 
 * @brief Type definition for memory usage pair 
   * @var typedef stdpairmemusage stdstring event 
 * @brief Type definition for event pair 
   * @fn MemUsageconst stdstringmsg start 
 * @brief Constructor for MemUsage class 
 * @param msg Message for memory usage 
   * @fn void pushconst stdstringmsg MemUsagememusage mu 
 * @brief Records an event with message and memory usage 
 * @param msg Message for the event 
 * @param mu Memory usage for the event 
   * @fn stdstring operatorstdstring msg stdmemusagemu 
 * @brief Records an event and returns a string representation 
 * @param msg Message for the event 
 * @param mu Memory usage for the event 
 * @return String representation of the event 
   * @fn stdstring summaryvoid 
 * @brief Returns a summary of recorded events 
 * @return Summary of events 
   * @fn event operatorint ind 
 * @brief Returns an event at a specified index 
 * @param ind Index of the event 
 * @return Event at the specified index 
   * @fn memusage currentvoid 
 * @brief Returns the current memory usage 
 * @return Current memory usage 
   * @var stdvectorevent m_events 
 * @brief Vector of recorded events 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
    class MemUsage {
    public:	
	typedef std::pair<double, double> memusage;
	typedef std::pair<memusage, std::string> event;
	MemUsage(const std::string& msg = "start");
	~MemUsage();

	void push(const std::string& msg, MemUsage::memusage mu = memusage(-1,-1));

	/// Record an event.
	std::string operator()(
	    std::string msg = "<tick>",
	    MemUsage::memusage mu = memusage(-1,-1));
	
	/// Return summary up to now.
	std::string summary() const;

	/// Return event by index.
	event operator[](int ind) const;
	
	memusage current() const;

    private:
	/// Emit a formatted message for the given event index.
	std::string emit(int ind) const;


	std::vector< event > m_events;

    };

}


#endif
