// http://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process
// http://stackoverflow.com/questions/669438/how-to-get-memory-usage-at-run-time-in-c

#ifndef WIRECELL_MEMUSAGE
#define WIRECELL_MEMUSAGE

#include <fstream>
#include <vector>
#include <string>


namespace WCP {

    double memusage_resident();
    double memusage_shared();
    double memusage_size();

    
/**assistant
 * @brief Class representing memory usage tracking functionality.
 *
 * Provides methods for recording events, retrieving summaries, and accessing individual events.
   * @brief Constructor for initializing memory usage tracking with an optional message.
 *
 * @param msg Optional message for initialization.
  * @brief Destructor for cleaning up resources.
  * @brief Records an event with an optional message and memory usage information.
 *
 * @param msg Message associated with the event.
 * @param mu Memory usage information.
  * @brief Operator for recording an event and returning a string representation.
 *
 * @param msg Message associated with the event.
 * @param mu Memory usage information.
 * @return String representation of the recorded event.
  * @brief Returns a summary of events up to the current point.
 *
 * @return Summary string.
  * @brief Subscript operator for accessing an event by index.
 *
 * @param ind Index of the event to access.
 * @return Event at the specified index.
  * @brief Returns the current memory usage information.
 *
 * @return Current memory usage.
  * @brief Private method for emitting a formatted message for a given event index.
 *
 * @param ind Index of the event.
 * @return Formatted message for the event.
  * @brief Vector storing recorded events.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
    class MemUsage {
    public:	
	typedef std::pair<double, double> memusage;
	typedef std::pair<memusage, std::string> event;
	MemUsage(const std::string& msg = "start");
	~MemUsage();

	void push(const std::string& msg, MemUsage::memusage mu = memusage(-1,-1));

	/// Record an event.
	std::string operator()(
	    std::string msg = "<tick>",
	    MemUsage::memusage mu = memusage(-1,-1));
	
	/// Return summary up to now.
	std::string summary() const;

	/// Return event by index.
	event operator[](int ind) const;
	
	memusage current() const;

    private:
	/// Emit a formatted message for the given event index.
	std::string emit(int ind) const;


	std::vector< event > m_events;

    };

}


#endif
