#ifndef WIRECELL_MERGETOYTILING_H
#define WIRECELL_MERGETOYTILING_H

#include "WCP2dToy/ToyTiling.h"

namespace WCP2dToy{
/**
 * @brief Merging of toy tiling objects.
 *
 * This class extends ToyTiling and provides functionality for merging 
 * GeomCells and handling wire associations. It includes methods for 
 * forming wire maps, getting cell selections, and performing further 
 * merges. Additionally, it has static methods for converting between 
 * time and distance units.
 
 
 * @brief Constructor.
 
  * @brief Copy constructor.
 * @param gds Detector geometry description.
 * @param tiling ToyTiling object.
 * @param time_slice Time slice index.
 
  * @brief Alternate copy constructor.
 * @param tiling ToyTiling object.
 * @param time_slice Time slice index.
 * @param merge_strategy Merge strategy identifier.
 * @param flag_remerge Flag indicating remerging.
 
  * @brief Destructor.
 
 * @brief Gets a GeomCell associated with the specified wires.
 * @param wires Selection of GeomWires.
 * @return Pointer to the associated GeomCell.
 
  * @brief Returns a selection of single-wire GeomCells.
 * @return Reference to the selection of single-wire GeomCells.
 
  * @brief Returns a selection of three-wire GeomCells.
 * @return Reference to the selection of three-wire GeomCells.
 
  * @brief Returns a selection of two-wire GeomCells.
 * @return Reference to the selection of two-wire GeomCells.
 
  * @brief Returns a mapping of merged cells to other merged cells.
 * @return Reference to the mapping of merged cells.
 
 * @brief Performs a further merge operation on the specified cells.
 * @param allcell Selection of GeomCells to merge.
 * @param ncell Number of cells.
 * @param time_slice Time slice index.
 * @param dis Distance threshold.
 * @return Result of the merge operation.
 
  * @brief Performs a further merge operation on the specified wires.
 * @param allwire Selection of GeomWires to merge.
 * @param nwire Number of wires.
 * @param time_slice Time slice index.
 * @return Result of the merge operation.
 
  * @brief Checks if remerging occurred.
 * @return True if remerging occurred, false otherwise.
 
 * @brief Converts time to distance.
 * @param time Time value.
 * @return Equivalent distance value.
 
  * @brief Converts distance to time.
 * @param dis Distance value.
 * @return Equivalent time value.
 
 * @brief Removes ghost cells from the specified selection.
 * @param good_mcells Selection of GeomCells to process.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class MergeToyTiling : public WCP2dToy::ToyTiling {
  public:
    MergeToyTiling(){};
    MergeToyTiling(const WCP::DetectorGDS& gds, WCP2dToy::ToyTiling& tiling, int time_slice = -1);
    MergeToyTiling(WCP2dToy::ToyTiling& tiling, int time_slice=-1, int merge_strategy = 3, int flag_remerge=0);
    ~MergeToyTiling();

    const WCP::GeomCell* cell(const WCP::GeomWireSelection& wires)const ;
    WCP::GeomCellSelection& get_single_wire_cells(){return single_wire_cells;};
    WCP::GeomCellSelection& get_three_wires_cells(){return three_wires_cells;};
    WCP::GeomCellSelection& get_two_wires_cells(){return two_wires_cells;};
    WCP::GeomCellCellsMap& get_not_compatible_cells_map(){ return mcmcsmap;};
    

    int further_merge(WCP::GeomCellSelection &allcell, int ncell, int time_slice, double dis = 0.2 * units::mm);
    int further_mergewire(WCP::GeomWireSelection &allwire, int nwire, int time_slice);
    bool GetRemerged(){return IsRemerged;};
    
    static double Time2Dis(int time){return time*time_convert + dis_offset;};
    static int Dis2Time(double dis){ return round((dis/units::cm-dis_offset)/time_convert);}; //in cm

    void deghost(WCP::GeomCellSelection& good_mcells); //used for MicroBooNE data ... 


  protected:
    bool IsRemerged;
    
    static double time_convert;
    static double dis_offset;


    void form_wiremap(WCP2dToy::ToyTiling& tiling, int time_slice);
    void form_wiremap(const WCP::DetectorGDS& gds, WCP2dToy::ToyTiling& tiling, int time_slice);

    WCP::GeomCellMap cellmap1;
    WCP::GeomWireMap wiremap1;

    WCP::GeomWireWireMap wwmap; // wire to merged wire
    WCP::GeomWireWiresMap wwsmap; // merged wire to wires
    
    WCP::GeomCellCellsMap mcmcsmap; //merged cell to merged cell map;

    WCP::GeomCellSelection single_wire_cells;
    WCP::GeomCellSelection three_wires_cells;
    WCP::GeomCellSelection two_wires_cells;

   ClassDef(MergeToyTiling,1);
  };
}
#endif
