#ifndef WIRECELL_MERGETOYTILING_H
#define WIRECELL_MERGETOYTILING_H

#include "WCP2dToy/ToyTiling.h"

namespace WCP2dToy{
/**
 * @brief Provides functionality for merging toy tilings in 2D space.
  
 * @brief Constructor for MergeToyTiling objects.
 
 * @brief Destructor for MergeToyTiling objects.
 
 * @brief Returns a constant pointer to a GeomCell object based on the input GeomWireSelection.
 * @param wires GeomWireSelection object used to retrieve the corresponding GeomCell.
 * @return Constant pointer to a GeomCell object.
 
 * @brief Retrieves the selection of cells formed by single wires.
 * @return Reference to a GeomCellSelection object containing cells formed by single wires.
 
 * @brief Retrieves the selection of cells formed by three wires.
 * @return Reference to a GeomCellSelection object containing cells formed by three wires.
 
 * @brief Retrieves the selection of cells formed by two wires.
 * @return Reference to a GeomCellSelection object containing cells formed by two wires.
 
 * @brief Retrieves the mapping of merged cells to incompatible cells.
 * @return Reference to a GeomCellCellsMap object containing the mapping.
 
 * @brief Performs further merging of cells based on the input parameters.
 * @param allcell Selection of cells to be merged.
 * @param ncell Number of cells in the selection.
 * @param time_slice Time slice value used for merging.
 * @param dis Distance threshold used for merging.
 * @return Integer indicating the result of the merging process.
 
 * @brief Performs further merging of wires based on the input parameters.
 * @param allwire Selection of wires to be merged.
 * @param nwire Number of wires in the selection.
 * @param time_slice Time slice value used for merging.
 * @return Integer indicating the result of the merging process.
 
 * @brief Checks if remerging has been performed.
 * @return Boolean indicating whether remerging has been done.
 
 * @brief Converts time to distance using a predefined conversion factor and offset.
 * @param time Input time value.
 * @return Converted distance value.
 
 * @brief Converts distance to time using a predefined conversion factor and offset.
 * @param dis Input distance value.
 * @return Converted time value.
 
 * @brief Removes ghost cells from the input selection.
 * @param good_mcells Selection of cells to be processed.
 
 * @brief Flag indicating whether remerging has been performed.
 
 * @brief Conversion factor used for time-to-distance conversions.
 
 * @brief Offset value used for time-to-distance conversions.
 
 * @brief Forms a wire map based on the input tiling and time slice.
 * @param tiling ToyTiling object used to create the wire map.
 * @param time_slice Time slice value used for creating the wire map.
 
 * @brief Forms a wire map based on the input GDS and tiling, and time slice.
 * @param gds DetectorGDS object used to create the wire map.
 * @param tiling ToyTiling object used to create the wire map.
 * @param time_slice Time slice value used for creating the wire map.
 
 * @brief Mapping of cells to their corresponding indices.
 
 * @brief Mapping of wires to their corresponding indices.
 
 * @brief Mapping of wires to merged wires.
 
 * @brief Mapping of merged wires to original wires.
 
 * @brief Mapping of merged cells to other merged cells.
 
 * @brief Selection of cells formed by single wires.
 
 * @brief Selection of cells formed by three wires.
 
 * @brief Selection of cells formed by two wires.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class MergeToyTiling : public WCP2dToy::ToyTiling {
  public:
    MergeToyTiling(){};
    MergeToyTiling(const WCP::DetectorGDS& gds, WCP2dToy::ToyTiling& tiling, int time_slice = -1);
    MergeToyTiling(WCP2dToy::ToyTiling& tiling, int time_slice=-1, int merge_strategy = 3, int flag_remerge=0);
    ~MergeToyTiling();

    const WCP::GeomCell* cell(const WCP::GeomWireSelection& wires)const ;
    WCP::GeomCellSelection& get_single_wire_cells(){return single_wire_cells;};
    WCP::GeomCellSelection& get_three_wires_cells(){return three_wires_cells;};
    WCP::GeomCellSelection& get_two_wires_cells(){return two_wires_cells;};
    WCP::GeomCellCellsMap& get_not_compatible_cells_map(){ return mcmcsmap;};
    

    int further_merge(WCP::GeomCellSelection &allcell, int ncell, int time_slice, double dis = 0.2 * units::mm);
    int further_mergewire(WCP::GeomWireSelection &allwire, int nwire, int time_slice);
    bool GetRemerged(){return IsRemerged;};
    
    static double Time2Dis(int time){return time*time_convert + dis_offset;};
    static int Dis2Time(double dis){ return round((dis/units::cm-dis_offset)/time_convert);}; //in cm

    void deghost(WCP::GeomCellSelection& good_mcells); //used for MicroBooNE data ... 


  protected:
    bool IsRemerged;
    
    static double time_convert;
    static double dis_offset;


    void form_wiremap(WCP2dToy::ToyTiling& tiling, int time_slice);
    void form_wiremap(const WCP::DetectorGDS& gds, WCP2dToy::ToyTiling& tiling, int time_slice);

    WCP::GeomCellMap cellmap1;
    WCP::GeomWireMap wiremap1;

    WCP::GeomWireWireMap wwmap; // wire to merged wire
    WCP::GeomWireWiresMap wwsmap; // merged wire to wires
    
    WCP::GeomCellCellsMap mcmcsmap; //merged cell to merged cell map;

    WCP::GeomCellSelection single_wire_cells;
    WCP::GeomCellSelection three_wires_cells;
    WCP::GeomCellSelection two_wires_cells;

   ClassDef(MergeToyTiling,1);
  };
}
#endif
