#ifndef WIRECELL_MERGETOYTILING_H
#define WIRECELL_MERGETOYTILING_H

#include "WCP2dToy/ToyTiling.h"

namespace WCP2dToy{
/**
 * @brief Provides functionality for merging toy tilings in 2D space.
  
 * @brief Constructor for MergeToyTiling objects.
 
 * @brief Destructor for MergeToyTiling objects.
 
 * @brief Returns a constant pointer to a GeomCell object based on a GeomWireSelection.
 * @param wires GeomWireSelection object.
 * @return Constant pointer to a GeomCell object.
 
 * @brief Returns a reference to a GeomCellSelection containing cells formed by single wires.
 * @return Reference to a GeomCellSelection object.
 
 * @brief Returns a reference to a GeomCellSelection containing cells formed by three wires.
 * @return Reference to a GeomCellSelection object.
 
 * @brief Returns a reference to a GeomCellSelection containing cells formed by two wires.
 * @return Reference to a GeomCellSelection object.
 
 * @brief Returns a reference to a GeomCellCellsMap mapping merged cells to other merged cells.
 * @return Reference to a GeomCellCellsMap object.
 
 * @brief Merges cells further based on certain criteria.
 * @param allcell GeomCellSelection object containing cells to be merged.
 * @param ncell Number of cells.
 * @param time_slice Time slice value.
 * @param dis Distance threshold value.
 * @return Integer indicating success or failure.
 
 * @brief Merges wires further based on certain criteria.
 * @param allwire GeomWireSelection object containing wires to be merged.
 * @param nwire Number of wires.
 * @param time_slice Time slice value.
 * @return Integer indicating success or failure.
 
 * @brief Checks if remerging has occurred.
 * @return Boolean indicating whether remerging has occurred.
 
 * @brief Converts time to distance.
 * @param time Time value.
 * @return Double representing the equivalent distance.
 
 * @brief Converts distance to time.
 * @param dis Distance value.
 * @return Integer representing the equivalent time.
 
 * @brief Removes ghost cells from a selection.
 * @param good_mcells GeomCellSelection object containing cells to be processed.
 
 * @brief Flag indicating whether remerging has occurred.
 
 * @brief Conversion factor for time to distance.
 
 * @brief Offset value for time to distance conversion.
 
 * @brief Forms a wire map based on a ToyTiling object and time slice.
 * @param tiling ToyTiling object.
 * @param time_slice Time slice value.
 
 * @brief Forms a wire map based on a DetectorGDS and ToyTiling object and time slice.
 * @param gds DetectorGDS object.
 * @param tiling ToyTiling object.
 * @param time_slice Time slice value.
 
 * @brief Map of GeomCell objects.
 
 * @brief Map of GeomWire objects.
 
 * @brief Map of merged wires to original wires.
 
 * @brief Map of merged wires to sets of original wires.
 
 * @brief Map of merged cells to other merged cells.
 
 * @brief Selection of GeomCell objects formed by single wires.
 
 * @brief Selection of GeomCell objects formed by three wires.
 
 * @brief Selection of GeomCell objects formed by two wires.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class MergeToyTiling : public WCP2dToy::ToyTiling {
  public:
    MergeToyTiling(){};
    MergeToyTiling(const WCP::DetectorGDS& gds, WCP2dToy::ToyTiling& tiling, int time_slice = -1);
    MergeToyTiling(WCP2dToy::ToyTiling& tiling, int time_slice=-1, int merge_strategy = 3, int flag_remerge=0);
    ~MergeToyTiling();

    const WCP::GeomCell* cell(const WCP::GeomWireSelection& wires)const ;
    WCP::GeomCellSelection& get_single_wire_cells(){return single_wire_cells;};
    WCP::GeomCellSelection& get_three_wires_cells(){return three_wires_cells;};
    WCP::GeomCellSelection& get_two_wires_cells(){return two_wires_cells;};
    WCP::GeomCellCellsMap& get_not_compatible_cells_map(){ return mcmcsmap;};
    

    int further_merge(WCP::GeomCellSelection &allcell, int ncell, int time_slice, double dis = 0.2 * units::mm);
    int further_mergewire(WCP::GeomWireSelection &allwire, int nwire, int time_slice);
    bool GetRemerged(){return IsRemerged;};
    
    static double Time2Dis(int time){return time*time_convert + dis_offset;};
    static int Dis2Time(double dis){ return round((dis/units::cm-dis_offset)/time_convert);}; //in cm

    void deghost(WCP::GeomCellSelection& good_mcells); //used for MicroBooNE data ... 


  protected:
    bool IsRemerged;
    
    static double time_convert;
    static double dis_offset;


    void form_wiremap(WCP2dToy::ToyTiling& tiling, int time_slice);
    void form_wiremap(const WCP::DetectorGDS& gds, WCP2dToy::ToyTiling& tiling, int time_slice);

    WCP::GeomCellMap cellmap1;
    WCP::GeomWireMap wiremap1;

    WCP::GeomWireWireMap wwmap; // wire to merged wire
    WCP::GeomWireWiresMap wwsmap; // merged wire to wires
    
    WCP::GeomCellCellsMap mcmcsmap; //merged cell to merged cell map;

    WCP::GeomCellSelection single_wire_cells;
    WCP::GeomCellSelection three_wires_cells;
    WCP::GeomCellSelection two_wires_cells;

   ClassDef(MergeToyTiling,1);
  };
}
#endif
