#ifndef WIRECELL2dToy_PD_DATA_FDS_H
#define WIRECELL2dToy_PD_DATA_FDS_H

#include "WCPNav/FrameDataSource.h"
#include "WCPNav/GeomDataSource.h"

#include "TH2F.h"


namespace WCP2dToy{
/**
 * @brief Data source class for frame data 
 * @details Provides functionality for managing and refreshing frame data
 * @ingroup DataSources
 
class pdDataFDS : public WCP::FrameDataSource
{
  public:
         * @brief Constructor for integer histogram type
     * @param gds Geom data source
     * @param hu Histogram u
     * @param hv Histogram v
     * @param hw Histogram w
     * @param eve_num Event number
     
    pdDataFDS(const WCP::GeomDataSource& gds, TH2I *hu, TH2I *hv, TH2I *hw, int eve_num);

         * @brief Constructor for float histogram type
     * @param gds Geom data source
     * @param hu Histogram u
     * @param hv Histogram v
     * @param hw Histogram w
     * @param eve_num Event number
     
    pdDataFDS(const WCP::GeomDataSource& gds, TH2F *hu, TH2F *hv, TH2F *hw, int eve_num);

         * @brief Destructor
     
    ~pdDataFDS();

         * @brief Refreshes the deconvoluted histograms
     * @param hu_decon Deconvoluted histogram u
     * @param hv_decon Deconvoluted histogram v
     * @param hw_decon Deconvoluted histogram w
     * @param eve_num Event number
     
    void refresh(TH2F *hu_decon, TH2F *hv_decon, TH2F *hw_decon, int eve_num);
    
         * @brief Jumps to a specified frame number
     * @param frame_number Frame number to jump to
     * @return Status of the operation
     
    virtual int jump(int frame_number);

         * @brief Returns the size of the data source
     * @return Size of the data source
     
    virtual int size() const;

  private:
         * @brief Geom data source reference
     
    const WCP::GeomDataSource& gds;

         * @brief Number of wires in u direction
     
    int nwire_u;

         * @brief Number of wires in v direction
     
    int nwire_v;

         * @brief Number of wires in w direction
     
    int nwire_w;
}* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class pdDataFDS : public WCP::FrameDataSource
  {
  public:
    pdDataFDS(const WCP::GeomDataSource& gds, TH2I *hu, TH2I *hv, TH2I *hw, int eve_num);
    pdDataFDS(const WCP::GeomDataSource& gds, TH2F *hu, TH2F *hv, TH2F *hw, int eve_num);
    ~pdDataFDS();

    void refresh(TH2F *hu_decon, TH2F *hv_decon, TH2F *hw_decon, int eve_num);
    
    virtual int jump(int frame_number);
    virtual int size() const;

  private:
    const WCP::GeomDataSource& gds;
    int nwire_u;
    int nwire_v;
    int nwire_w;
  };

}
#endif
