#ifndef WIRECELL_TOTALTILING_H
#define WIRECELL_TOTALTILING_H
#include "WCPData/GeomCell.h"
#include "WCPData/GeomWire.h"
#include "WCPData/GeomWCPMap.h"

namespace WCP2dToy {
/** * @brief Manages the tiling of geometric cells with associated wires in a liquid argon time projection chamber.
 *
 * This class facilitates the association between geometric cells and their corresponding wires (U, V, W) used in the detection process within a liquid argon time projection chamber setup.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
  class TotalTiling {
    public:
    TotalTiling();
    ~TotalTiling();
    
    void AddCellWire(const WCP::GeomCell *cell, const WCP::GeomWire *uwire, const WCP::GeomWire *vwire, const WCP::GeomWire *wwire);
    
    WCP::GeomWireSelection wires(const WCP::GeomCell& cell) const;
    WCP::GeomCellSelection cells(const WCP::GeomWire& wire) const;
    const WCP::GeomCell* cell(const WCP::GeomWireSelection& wires);
    void Clear();
  
    WCP::GeomWireSelection wire_u;
    WCP::GeomWireSelection wire_v;
    WCP::GeomWireSelection wire_w;

    WCP::GeomWireSelection wire_all;
    
    WCP::GeomCellSelection cell_all;

    WCP::GeomCellMap cellmap;
    WCP::GeomWireMap wiremap;
  };
  

}

#endif
