#ifndef WIRECELL_TOTALTILING_H
#define WIRECELL_TOTALTILING_H
#include "WCPData/GeomCell.h"
#include "WCPData/GeomWire.h"
#include "WCPData/GeomWCPMap.h"

namespace WCP2dToy {
/** * @brief Manages the tiling of geometric cells with associated wires.
 *
 * This class provides functionality to add cells along with their corresponding u, v, and w wires,
 * retrieve wires associated with a particular cell, find cells connected to a set of wires,
 * identify a single cell from multiple wires, clear all stored data, and maintain mappings between cells and wires.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.01.
*/ 
  class TotalTiling {
    public:
    TotalTiling();
    ~TotalTiling();
    
    void AddCellWire(const WCP::GeomCell *cell, const WCP::GeomWire *uwire, const WCP::GeomWire *vwire, const WCP::GeomWire *wwire);
    
    WCP::GeomWireSelection wires(const WCP::GeomCell& cell) const;
    WCP::GeomCellSelection cells(const WCP::GeomWire& wire) const;
    const WCP::GeomCell* cell(const WCP::GeomWireSelection& wires);
    void Clear();
  
    WCP::GeomWireSelection wire_u;
    WCP::GeomWireSelection wire_v;
    WCP::GeomWireSelection wire_w;

    WCP::GeomWireSelection wire_all;
    
    WCP::GeomCellSelection cell_all;

    WCP::GeomCellMap cellmap;
    WCP::GeomWireMap wiremap;
  };
  

}

#endif
