#ifndef WIRECELL_TOYCOSMIC_H
#define WIRECELL_TOYCOSMIC_H

#include "WCP2dToy/ToyTracking.h"
#include "WCP2dToy/WCCosmic.h"

namespace WCP2dToy{
/**
 * @brief Class representing toy cosmic tracking selection
 * @details Provides functionality for managing toy cosmic tracking data
 * @author unknown
  
 * @class ToyCosmic
 * @brief Manages toy cosmic tracking data and provides related operations
 * @ingroup Tracking
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class ToyCosmic{
  public:
    ToyCosmic(ToyTrackingSelection& trackings, float abc = 10, float abc1 = 3);
    ~ToyCosmic();
    
    std::vector<ToyTrackingSelection>& get_raw_candidates(){return cosmic_candidates;};
    ToyTrackingSelection& get_neutrinos(){return nocosmic_trackings;};

    bool IsConnected(ToyTracking *tracking1, ToyTracking *tracking2);
    bool IsConnected(WCP::MergeSpaceCell *mcell1, WCP::MergeSpaceCell *mcell2, float dis_cut);
    
    WCCosmicSelection& get_cosmics(){return cosmics;};
    
  protected:
    ToyTrackingSelection& trackings;
    ToyTrackingSelection nocosmic_trackings;
    WCCosmicSelection cosmics;
    std::vector<ToyTrackingSelection> cosmic_candidates;

    float gap_cut;
    float gap_cut1;
  };
}

#endif
