#ifndef WIRECELL_TOYHYPOTHESIS_H
#define WIRECELL_TOYHYPOTHESIS_H

#include "WCPData/MergeGeomCell.h"

namespace WCP2dToy{
/**
 * @brief Represents a toy hypothesis for geometric calculations.
 * 
 * This class provides methods for calculating values and checking points inside cells.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class ToyHypothesis {
  public:
    ToyHypothesis();
    ToyHypothesis(WCP::MergeGeomCell& mcell1, WCP::MergeGeomCell& mcell2);
    ~ToyHypothesis();
    double CalValue(WCP::Point p, WCP::Point p1, WCP::Point p2);
    bool IsInside(WCP::Point p);
    bool IsInside(const WCP::GeomCell& cell);
    
    
  private:
    WCP::Point p1[2],p2[2],pc[2];
  };
  typedef std::vector<const WCP2dToy::ToyHypothesis*> HypoSelection;
}


#endif
