#ifndef WIRECELL_TOYMATRIXKALMAN_H
#define WIRECELL_TOYMATRIXKALMAN_H

#include "WCP2dToy/ToyMatrix.h"
#include "TMatrixDEigen.h"

namespace WCP2dToy {
/**
 * @brief Class representing a Kalman filter for toy matrices.
 *
 * This class provides functionality for initializing and updating a Kalman filter
 * for toy matrices, including calculating the number of zeros in the matrix,
 * setting penalties, and accessing various parameters.
  
 * @brief Class representing a ToyMatrixKalman object constructor.
 *
 * Initializes a ToyMatrixKalman object with a toy matrix and optional flags and penalty.
  
 * @brief Class representing a ToyMatrixKalman object destructor.
 *
 * Releases resources allocated by the ToyMatrixKalman object.
  
 * @brief Returns the number of zeros in the matrix.
 *
 * @return The number of zeros in the matrix.
  
 * @brief Returns the number of solves performed.
 *
 * @return The number of solves performed.
  
 * @brief Returns the list of already removed elements.
 *
 * @return The list of already removed elements.
  
 * @brief Returns the list of elements that do not need to be removed.
 *
 * @return The list of elements that do not need to be removed.
  
 * @brief Returns the index of the most constrained element.
 *
 * @return The index of the most constrained element.
  
 * @brief Calculates the number of zeros in the given toy matrix.
 *
 * @param toymatrix The input toy matrix.
 * @return The number of zeros in the matrix.
  
 * @brief Initializes the Kalman filter with the given toy matrix.
 *
 * @param toymatrix The input toy matrix.
  
 * @brief Sets the penalty value for the Kalman filter.
 *
 * @param val The new penalty value.
  
 * @brief Flag indicating whether certain operations are not needed.
 *
 * Protected member variable.
  
 * @brief Penalty value used in the Kalman filter calculations.
 *
 * Protected member variable.
  
 * @brief List of already removed elements.
 *
 * Protected member variable.
  
 * @brief List of elements that do not need to be removed.
 *
 * Protected member variable.
  
 * @brief Number of zeros in the matrix.
 *
 * Protected member variable.
  
 * @brief Number of solves performed.
 *
 * Protected member variable.
  
 * @brief Index of the most constrained element.
 *
 * Protected member variable.
  
 * @brief Index of the most weighted element.
 *
 * Protected member variable.
  
 * @brief Index of the smallest weighted element.
 *
 * Protected member variable.
  
 * @brief Eigenvalue decomposition data structure.
 *
 * Protected member variable.
  
 * @brief Eigenvector data structure.
 *
 * Protected member variable.
  
 * @brief Check flag for internal consistency.
 *
 * Protected member variable.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class ToyMatrixKalman {
  public:
    ToyMatrixKalman(WCP2dToy::ToyMatrix &toymatrix, int flag_no_need=1, double chi2_penalty = 0);
    ToyMatrixKalman(std::vector<int>& already_removed1, std::vector<int>& no_need_remove1 ,WCP2dToy::ToyMatrix &toymatrix, int check, int flag_no_need=1, double chi2_penalty = 0);
    virtual ~ToyMatrixKalman();

    int Get_numz(){return numz;};
    int Get_ncount(){return ncount;};
    std::vector<int>& Get_already_removed(){return already_removed;};
    std::vector<int>& Get_no_need_remove(){return no_need_remove;};
    int Get_mcindex(){return mcindex;};
    int Cal_numz(WCP2dToy::ToyMatrix &toymatrix);
    void init(WCP2dToy::ToyMatrix &toymatrix);
    void Set_penalty(double val){chi2_penalty = val;}

  protected:
    int flag_no_need;
    double chi2_penalty;

    std::vector<int> already_removed;
    std::vector<int> no_need_remove;
    
    int numz; //number of zeros in the matrix
    int ncount; // how many solve was done
    
    int mcindex;
    int mwindex;
    int swindex;

    TMatrixDEigen *Eigen;
    TVectorD *EigenValue;

    int check_flag;

    /* TMatrixD *MA, *MAT; */
    /* TMatrixD *MC, *MC_inv; */
  };
}
#endif
