#ifndef TOYMATRIXITERATE_ONLY_H
#define TOYMATRIXITERATE_ONLY_H

#include "WCP2dToy/ToyMatrix.h"
#include "WCP2dToy/MergeToyTiling.h"
#include "WCP2dToy/ToyMatrixKalman.h"

namespace WCP2dToy{
/**
 * Brief description of the class 
 * Detailed description of the class 
  
class ToyMatrixIterate_Only { * Constructor for ToyMatrixIterate_Only class 
 * @param toymatrix reference to WCP2dToyToyMatrix object 
 * @param mergetiling pointer to WCP2dToyMergeToyTiling object 
  * Destructor for ToyMatrixIterate_Only class 
  * Protected member variable toymatrix of type WCP2dToyToyMatrix 
  * Protected member variable mergetiling of type pointer to WCP2dToyMergeToyTiling 
  * Protected member variable wirechargemap of type WCPWireChargeMap 
  * Protected member variable cellmap of type WCPEGomCellMap 
  * Protected member variable allcells of type WCPEGomCellSelection 
  * Protected member function Iterate 
 * @param remainingcells of type WCPEGomCellSelection 
 * @param goodcells of type WCPEGomCellSelection 
 * @param usedwires of type WCPEGemWireSelection 
 * @param badcells of type WCPEGomCellSelection 
 * @param triedcells of type reference to WCPEGomCellSelection 
  * Protected member variable ncount of type integer 
  * Protected member variable nlevel of type integer 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class ToyMatrixIterate_Only{
  public:
    ToyMatrixIterate_Only(WCP2dToy::ToyMatrix& toymatrix, WCP2dToy::MergeToyTiling* mergetiling);
    ~ToyMatrixIterate_Only();
    

  protected:
     WCP2dToy::ToyMatrix &toymatrix;
     WCP2dToy::MergeToyTiling *mergetiling;
     WCP::WireChargeMap wirechargemap;
     WCP::GeomCellMap cellmap;
     
     WCP::GeomCellSelection all_cells;
     
     void Iterate(WCP::GeomCellSelection remaining_cells, 
		  WCP::GeomCellSelection good_cells,
		  WCP::GeomWireSelection used_wires,
		  WCP::GeomCellSelection bad_cells,
		  WCP::GeomCellSelection& tried_cells);

     int ncount;
     int nlevel;
     
  };
}

#endif

