#ifndef TOYMATRIXITERATE_ONLY_H
#define TOYMATRIXITERATE_ONLY_H

#include "WCP2dToy/ToyMatrix.h"
#include "WCP2dToy/MergeToyTiling.h"
#include "WCP2dToy/ToyMatrixKalman.h"

namespace WCP2dToy{
/**
 * Brief description of the class 
 * Detailed description of the class 
  
class ToyMatrixIterate_Only { * Constructor for ToyMatrixIterate_Only class 
 * @param toymatrix reference to WCP2dToy ToyMatrix object 
 * @param mergetiling pointer to WCP2dToy MergeToyTiling object 
  * Destructor for ToyMatrixIterate_Only class 
  * Protected member variable toymatrix of type WCP2dToy ToyMatrix 
  * Protected member variable mergetiling of type pointer to WCP2dToy MergeToyTiling 
  * Protected member variable wirechargemap of type WCP WireChargeMap 
  * Protected member variable cellmap of type WCP GeomCellMap 
  * Protected member variable all_cells of type WCP GeomCellSelection 
  * Protected member function Iterate 
 * @param remaining_cells of type WCP GeomCellSelection 
 * @param good_cells of type WCP GeomCellSelection 
 * @param used_wires of type WCP GeomWireSelection 
 * @param bad_cells of type WCP GeomCellSelection 
 * @param tried_cells of type WCP GeomCellSelection 
  * Protected member variable ncount of type integer 
  * Protected member variable nlevel of type integer 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class ToyMatrixIterate_Only{
  public:
    ToyMatrixIterate_Only(WCP2dToy::ToyMatrix& toymatrix, WCP2dToy::MergeToyTiling* mergetiling);
    ~ToyMatrixIterate_Only();
    

  protected:
     WCP2dToy::ToyMatrix &toymatrix;
     WCP2dToy::MergeToyTiling *mergetiling;
     WCP::WireChargeMap wirechargemap;
     WCP::GeomCellMap cellmap;
     
     WCP::GeomCellSelection all_cells;
     
     void Iterate(WCP::GeomCellSelection remaining_cells, 
		  WCP::GeomCellSelection good_cells,
		  WCP::GeomWireSelection used_wires,
		  WCP::GeomCellSelection bad_cells,
		  WCP::GeomCellSelection& tried_cells);

     int ncount;
     int nlevel;
     
  };
}

#endif

