#ifndef WIRECELL_TOYWALKING_H
#define WIRECELL_TOYWALKING_H

#include "WCPData/MergeSpaceCell.h"

namespace WCP2dToy{
/**
 * Brief description of the class 
 * Detailed description of the class 
  
class ToyWalking { * Constructor for ToyWalking with six parameters 
 * @param start_cell starting cell 
 * @param start_point starting point 
 * @param target_cell target cell 
 * @param target_point target point 
 * @param mcells_map map of merge space cells 
 * @param counter_limit limit for counter with default value 1000 
  * Constructor for ToyWalking with seven parameters 
 * @param start_cell starting cell 
 * @param start_point starting point 
 * @param target_cell target cell 
 * @param target_point target point 
 * @param mcells_map map of merge space cells 
 * @param must_cells selection of merge space cells 
 * @param counter_limit limit for counter with default value 1000 
  * Destructor for ToyWalking 
  * Iterates over current cell and updates distance and cells 
 * @param curr_cell current cell 
 * @param curr_cells current selection of cells 
 * @param dis distance 
  * Returns the selected cells 
 * @return cells 
  * Returns the calculated distance 
 * @return dist 
  * Returns the counter value 
 * @return counter 
  * Returns the global counter value 
 * @return global_counter 
 
protected: * Distance variable 
  * Selected cells 
  * Starting cell 
  * Target cell 
  * Map of merge space cells 
  * Starting point 
  * Target point 
  * Selection of mandatory cells 
  * Global counter 
  * Counter 
  * Limit for counter 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class ToyWalking{
  public:
    ToyWalking(WCP::MergeSpaceCell *start_cell, WCP::Point start_point, WCP::MergeSpaceCell *target_cell, WCP::Point target_point, WCP::MergeSpaceCellMap& mcells_map, int counter_limit=1000);
    ToyWalking(WCP::MergeSpaceCell *start_cell, WCP::Point start_point, WCP::MergeSpaceCell *target_cell, WCP::Point target_point, WCP::MergeSpaceCellMap& mcells_map, WCP::MergeSpaceCellSelection must_cells, int counter_limit=1000);

   

    ~ToyWalking();
    
    void Iterate(WCP::MergeSpaceCell *curr_cell, WCP::MergeSpaceCellSelection &curr_cells, double dis);
    
    WCP::MergeSpaceCellSelection get_cells(){return cells;};
    double get_dist(){return dist;};
    int get_counter(){return counter;};
    int get_global_counter(){return global_counter;};

  protected:
    double dist;
    WCP::MergeSpaceCellSelection cells;


    WCP::MergeSpaceCell *start_cell;
    WCP::MergeSpaceCell *target_cell;    
    WCP::MergeSpaceCellMap& mcells_map;
    WCP::Point start_point;
    WCP::Point target_point;

    WCP::MergeSpaceCellSelection must_cells;

    int global_counter;
    
    int counter;
    int counter_limit;
  };

/**
 * Brief description of the class purpose 
 * Detailed description of the class functionality and usage
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
  class ToyNWalking{
  public:
    ToyNWalking(WCP::MergeSpaceCell *start_cell, WCP::MergeSpaceCellMap& mcells_map, WCP::MergeSpaceCellSelection& used_cell, WCP::MergeSpaceCellSelection& must_cell);
    ~ToyNWalking();
    WCP::MergeSpaceCellSelection get_cells(){return cells;};
    void Iterate(WCP::MergeSpaceCell *curr_cell);
    
  protected:
    WCP::MergeSpaceCellSelection cells;
    
    WCP::MergeSpaceCell *start_cell;
    WCP::MergeSpaceCellMap& mcells_map;
    
    WCP::MergeSpaceCellSelection& must_cell;
    WCP::MergeSpaceCellSelection& used_cell;
  };

}

#endif
