#ifndef WIRECELL_TOYWALKING_H
#define WIRECELL_TOYWALKING_H

#include "WCPData/MergeSpaceCell.h"

namespace WCP2dToy{
/**
 * Brief description of the class 
 * Detailed description of the class 
   * Class representing toy walking functionality 
 * Provides methods for iterating through merge space cells 
 * and tracking distance and counters 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class ToyWalking{
  public:
    ToyWalking(WCP::MergeSpaceCell *start_cell, WCP::Point start_point, WCP::MergeSpaceCell *target_cell, WCP::Point target_point, WCP::MergeSpaceCellMap& mcells_map, int counter_limit=1000);
    ToyWalking(WCP::MergeSpaceCell *start_cell, WCP::Point start_point, WCP::MergeSpaceCell *target_cell, WCP::Point target_point, WCP::MergeSpaceCellMap& mcells_map, WCP::MergeSpaceCellSelection must_cells, int counter_limit=1000);

   

    ~ToyWalking();
    
    void Iterate(WCP::MergeSpaceCell *curr_cell, WCP::MergeSpaceCellSelection &curr_cells, double dis);
    
    WCP::MergeSpaceCellSelection get_cells(){return cells;};
    double get_dist(){return dist;};
    int get_counter(){return counter;};
    int get_global_counter(){return global_counter;};

  protected:
    double dist;
    WCP::MergeSpaceCellSelection cells;


    WCP::MergeSpaceCell *start_cell;
    WCP::MergeSpaceCell *target_cell;    
    WCP::MergeSpaceCellMap& mcells_map;
    WCP::Point start_point;
    WCP::Point target_point;

    WCP::MergeSpaceCellSelection must_cells;

    int global_counter;
    
    int counter;
    int counter_limit;
  };

/**
 * Brief description of the class purpose 
 * Detailed description of the class functionality and usage
  
class ToyNWalking { * Constructor to initialize the object with required parameters
 * @param start_cell starting cell for the walking process
 * @param mcells_map map of merge space cells
 * @param used_cell selection of used cells
 * @param must_cell selection of mandatory cells
  * Destructor to free up allocated resources
  * Method to retrieve the selected cells
 * @return collection of selected cells
  * Method to perform iteration over the current cell
 * @param curr_cell current cell being processed
  * Collection of selected cells
  * Starting point for the walking process
  * Reference to the map of merge space cells
  * Reference to the selection of mandatory cells
  * Reference to the selection of used cells
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
  class ToyNWalking{
  public:
    ToyNWalking(WCP::MergeSpaceCell *start_cell, WCP::MergeSpaceCellMap& mcells_map, WCP::MergeSpaceCellSelection& used_cell, WCP::MergeSpaceCellSelection& must_cell);
    ~ToyNWalking();
    WCP::MergeSpaceCellSelection get_cells(){return cells;};
    void Iterate(WCP::MergeSpaceCell *curr_cell);
    
  protected:
    WCP::MergeSpaceCellSelection cells;
    
    WCP::MergeSpaceCell *start_cell;
    WCP::MergeSpaceCellMap& mcells_map;
    
    WCP::MergeSpaceCellSelection& must_cell;
    WCP::MergeSpaceCellSelection& used_cell;
  };

}

#endif
