
#include <lsp/nnls.h>

#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/vector.hpp>
#include <boost/numeric/ublas/io.hpp>

#include <sstream>

/**
 * Main program entry point.
 *
 * This function initializes a linear least squares problem,
 * solves it using the nonnegative least squares algorithm,
 * and prints the solution and chi-squared value.
  
 * Initializes the coefficient matrix A and right-hand side vector b.
 *
 * Sets up a sample linear least squares problem.
 
 * Solves the nonnegative least squares problem Ax = b.
 *
 * Uses the nnls solver to find the nonnegative solution vector x
 * and computes the covariance matrix.
 *
 * @param x output solution vector
 * @param cov output covariance matrix
 
 * Prints the solution vector x.
 *
 * Outputs each element of the solution vector to the console.
 
 * Computes the residual vector r = Ax - b.
 *
 * Calculates the difference between the predicted and actual values.
 *
 * @return residual vector r
 
 * Computes the chi-squared value of the residual vector r.
 *
 * Calculates the sum of the squared elements of the residual vector.
 *
 * @return chi-squared value
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
int main(){
  using namespace boost::numeric::ublas;
  int m = 6, n=5;
  matrix< double > A(n,m);
  vector< double > b(n);
  A(0,3) = 1; A(0,4) = 1; A(0,5) = 1;
  A(1,0) = 1; A(1,1) = 1; A(1,2) = 1;
  A(2,2) = 1; A(2,5) = 1;
  A(3,1) = 1; A(3,4) = 1;
  A(4,0) = 1; A(4,3) = 1;
  
  b(0) = 28.7355;
  b(1) = 7.86395;
  b(2) = 18.0824;
  b(3) = 15.8977;
  b(4) = 2.61937;

  lsp::nnls< matrix< double >, vector< double >  > nnls( A, b );
  vector< double > x(m);
  matrix< double > cov(m,m);
  nnls.solve( x , cov );

  for (int i=0;i!=m;i++){
    std::cout << x(i) << std::endl;
  }
  
  vector<double> r = prod(A,x) -b;
  std::cout << "Chi2: " <<  inner_prod(r,r) << std::endl;
}
