
#include <lsp/nnls.h>

#include <boost/numeric/ublas/matrix.hpp>
#include <boost/numeric/ublas/vector.hpp>
#include <boost/numeric/ublas/io.hpp>

#include <sstream>

/**
 * @brief Main program entry point
 * 
 * This function initializes a linear least squares problem, 
 * solves it using the nonnegative least squares algorithm, 
 * and prints the solution and chi-squared value.
 * 
 * @return Program exit status
  
 * @brief Initialize coefficient matrix A and right-hand side vector b
 * 
 * Sets up a sample linear least squares problem with predefined coefficients.
 
 * @brief Solve nonnegative least squares problem Ax = b
 * 
 * Uses the nnls solver to find the nonnegative solution vector x 
 * and computes the covariance matrix.
 * 
 * @param x Output solution vector
 * @param cov Output covariance matrix
 
 * @brief Print solution vector x
 * 
 * Outputs each element of the solution vector to the console.
 
 * @brief Compute residual vector r = Ax - b
 * 
 * Calculates the difference between the predicted and actual values.
 
 * @brief Calculate and print Chi2 value
 * 
 * Computes the sum of squared residuals and prints the result.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
int main(){
  using namespace boost::numeric::ublas;
  int m = 6, n=5;
  matrix< double > A(n,m);
  vector< double > b(n);
  A(0,3) = 1; A(0,4) = 1; A(0,5) = 1;
  A(1,0) = 1; A(1,1) = 1; A(1,2) = 1;
  A(2,2) = 1; A(2,5) = 1;
  A(3,1) = 1; A(3,4) = 1;
  A(4,0) = 1; A(4,3) = 1;
  
  b(0) = 28.7355;
  b(1) = 7.86395;
  b(2) = 18.0824;
  b(3) = 15.8977;
  b(4) = 2.61937;

  lsp::nnls< matrix< double >, vector< double >  > nnls( A, b );
  vector< double > x(m);
  matrix< double > cov(m,m);
  nnls.solve( x , cov );

  for (int i=0;i!=m;i++){
    std::cout << x(i) << std::endl;
  }
  
  vector<double> r = prod(A,x) -b;
  std::cout << "Chi2: " <<  inner_prod(r,r) << std::endl;
}
