#include "WCPSst/GeomDataSource.h"
//#include "WCPSst/ToyuBooNEFrameDataSource.h"
#include "WCPSst/ToyuBooNESliceDataSource.h"
#include "WCP2dToy/ToyEventDisplay.h"
#include "WCP2dToy/ToyTiling.h"
#include "WCP2dToy/MergeToyTiling.h"
#include "WCP2dToy/TruthToyTiling.h"
#include "WCPData/MergeGeomCell.h"
#include "WCPData/GeomCluster.h"
//#include "WCPNav/SliceDataSource.h"

#include "WCPNav/FrameDataSource.h"
#include "WCPNav/SimDataSource.h"
#include "WCPNav/SliceDataSource.h"
#include "WCPSst/Util.h"
#include "WCPData/SimTruth.h"
#include "WCP2dToy/ToyDepositor.h"
#include "WCPNav/GenerativeFDS.h"


#include "TApplication.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TH1F.h"
#include "TFile.h"
#include "TGraph2D.h"
#include "TFile.h"
#include <iostream>
using namespace WCP;
using namespace std;




/**
 * @brief Main program entry point.
 *
 * This function initializes the application, sets up the data sources, 
 * performs simulations, and displays the results.
 *
 * @param argc Number of command line arguments.
 * @param argv Array of command line argument strings.
 * @return Exit status of the program.
  
 * @brief Checks command line argument count and prints usage message if insufficient.
 *
 * @return Error message if insufficient arguments.
 
if (argc < 3) {
}
 * @brief Creates a geometry data source object from file specified by first command line argument.
 
WCPSst::GeomDataSource gds(argv[1]);
 * @brief Retrieves extent of geometry data source.
 *
 * @return Vector of doubles representing extent.
 
std::vector<double> ex = gds.extent();
 * @brief Prints extent of geometry data source to standard error stream.
 
cerr << "Extent: "
     << " x:" << ex[0]/units::mm << " mm"
     << " y:" << ex[1]/units::m << " m"
     << " z:" << ex[2]/units::m << " m"
     << endl;
 * @brief Sets the path to the root file.
 
const char* root_file = argv[2];
 * @brief Creates a frame data source object.
 
WCP::FrameDataSource* fds = 0;
fds = WCPSst::make_fds(root_file);
 * @brief Checks if frame data source object creation was successful.
 
if (!fds) {
}
 * @brief Creates a toy depositor object.
 
WCP::ToyDepositor toydep(fds);
 * @brief Retrieves depositions from toy depositor.
 *
 * @return Vector of point values.
 
const PointValueVector pvv = toydep.depositions(1);
 * @brief Creates a generative frame data source object.
 
WCP::GenerativeFDS gfds(toydep,gds,2400,5,2.0*1.6*units::millimeter);
 * @brief Jumps to a specific point in the generative frame data source.
 
gfds.jump(1);
 * @brief Creates a ToYuBooNE slice data source object with a threshold of 2000 electrons.
 
WCPSst::ToYuBooNESliceDataSource sds(gfds,1500);
 * @brief Defines an array to store x, y, and z coordinates.
 
const int N = 100000;
Double_t x[N],y[N],z[N];
 * @brief Iterates over slices in the ToYuBooNE slice data source.
 
for (int i=0; i!=sds.size();i++) {
 * @brief Jumps to a specific slice in the ToYuBooNE slice data source.
 
sds.jump(i);
 * @brief Retrieves the current slice.
 *
 * @return Slice object.
 
WCP::Slice slice = sds.get();
 * @brief Checks if the slice has any groups.
 
if ( slice.group().size() >0){
 * @brief Creates a toy tiling object from the slice and geometry data source.
 
WCP2dToy::ToyTiling toytiling(slice,gds);
 * @brief Retrieves all cells in the toy tiling object.
 *
 * @return Selection of geom cells.
 
GeomCellSelection allcell = toytiling.get_allcell();
 * @brief Iterates over cells in the selection.
 
for (int j=0;j!=allcell.size();j++){
 * @brief Retrieves the center point of a cell.
 *
 * @return Point object.
 
Point p = allcell[j]->center();
 * @brief Stores x, y, and z coordinates in arrays.
 
x[ncount] = i*0.32;
y[ncount] = p.y/units::cm;
z[ncount] = p.z/units::cm;
ncount ++;
}
}
}
 * @brief Creates a ROOT application object.
 
TApplication theApp("theApp",&argc,argv);
 * @brief Configures the ROOT application.
 
theApp.SetReturnFromRun(true);
 * @brief Creates a ROOT canvas object.
 
TCanvas c1("ToyMC","ToyMC",800,600);
 * @brief Draws the canvas.
 
c1.Draw();
 * @brief Configures the ROOT graphics style.
 
gStyle->SetOptStat(0);
 * @brief Creates a 2D graph object from x, y, and z coordinates.
 
TGraph2D *g = new TGraph2D(ncount,x,y,z);
 * @brief Draws the graph.
 
g->Draw("p");
 * @brief Opens a ROOT file for writing.
 
TFile *file = new TFile("shower3D.root","RECREATE");
 * @brief Writes the graph to the file.
 
g->Write("shower3D");
 * @brief Writes the file to disk.
 
file->Write();
 * @brief Closes the file.
 
file->Close();
 * @brief Runs the ROOT application event loop.
 
//theApp.Run();
 * @brief Returns the program exit status.
 
return 0;* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
int main(int argc, char* argv[])
{
  if (argc < 3) {
      cerr << "usage: wire-cell-uboone /path/to/ChannelWireGeometry.txt /path/to/celltree.root" << endl;
      return 1;
  }


  WCPSst::GeomDataSource gds(argv[1]);
  std::vector<double> ex = gds.extent();
  cerr << "Extent: "
       << " x:" << ex[0]/units::mm << " mm"
       << " y:" << ex[1]/units::m << " m"
       << " z:" << ex[2]/units::m << " m"
       << endl;


  const char* root_file = argv[2];
  const char* tpath = "/Event/Sim";
  
  WCP::FrameDataSource* fds = 0;
  fds = WCPSst::make_fds(root_file);
  if (!fds) {
    cerr << "ERROR: failed to get FDS from " << root_file << endl;
    return 1;
  }
  

  
  WCP::ToyDepositor toydep(fds);
  const PointValueVector pvv = toydep.depositions(1);
  

  WCP::GenerativeFDS gfds(toydep,gds,2400,5,2.0*1.6*units::millimeter);
  gfds.jump(1);

  WCPSst::ToyuBooNESliceDataSource sds(gfds,1500); //set threshold at 2000 electrons
  
  const int N = 100000;
  Double_t x[N],y[N],z[N];
  
  int ncount = 0;
  //int i=1140;{
  
  for (int i=0; i!=sds.size();i++){
    sds.jump(i);
    WCP::Slice slice = sds.get();
    if ( slice.group().size() >0){
      WCP2dToy::ToyTiling toytiling(slice,gds);
      //WCP2dToy::MergeToyTiling mergetiling(toytiling);
      
      GeomCellSelection allcell = toytiling.get_allcell();
      
      for (int j=0;j!=allcell.size();j++){
	Point p = allcell[j]->center();
	x[ncount] = i*0.32;
	y[ncount] = p.y/units::cm;
	z[ncount] = p.z/units::cm;
	ncount ++;
      }
      
      // GeomCellSelection allmcell = mergetiling.get_allcell();
      // GeomWireSelection allwire = mergetiling.get_allwire();

      // cout << i << " " << allmcell.size() << " " << allwire.size() << endl;

      // int sum = 0;
      // for (int j=0;j!=allmcell.size();j++){
      //   sum += ((WCP::MergeGeomCell*)allmcell[j])->get_allcell().size() ;
      // }
      // cout << allcell.size() << " " << allmcell.size() << " "  << sum << endl;
      
      
    }
  }


  TApplication theApp("theApp",&argc,argv);
  theApp.SetReturnFromRun(true);
  
  TCanvas c1("ToyMC","ToyMC",800,600);
  c1.Draw();
  gStyle->SetOptStat(0);

  TGraph2D *g = new TGraph2D(ncount,x,y,z);
  g->Draw("p");

  TFile *file = new TFile("shower3D.root","RECREATE");
  g->Write("shower3D");
  file->Write();
  file->Close();

  //theApp.Run();
  return 0;
  
} // main()
