#include "WCPSst/GeomDataSource.h"
#include "WCPSst/DatauBooNEFrameDataSource.h"
#include "WCPSst/ToyuBooNESliceDataSource.h"
#include "WCP2dToy/ToyEventDisplay.h"
#include "WCP2dToy/ToyTiling.h"
#include "WCP2dToy/BadTiling.h"

#include "WCP2dToy/MergeToyTiling.h"
#include "WCP2dToy/TruthToyTiling.h"
#include "WCP2dToy/SimpleBlobToyTiling.h"

#include "WCP2dToy/ToyMatrix.h"
#include "WCP2dToy/ToyMatrixExclusive.h"
#include "WCP2dToy/ToyMatrixKalman.h"
#include "WCP2dToy/ToyMatrixIterate.h"
#include "WCP2dToy/ToyMatrixIterate_SingleWire.h"
#include "WCP2dToy/ToyMatrixIterate_Only.h"


#include "WCP2dToy/ToyMatrixMarkov.h"
#include "WCP2dToy/ToyMetric.h"
#include "WCP2dToy/BlobMetric.h"

#include "WCPData/MergeGeomCell.h"
#include "WCPData/MergeGeomWire.h"

#include "WCPData/GeomCluster.h"
//#include "WCPNav/SliceDataSource.h"


#include "WCPNav/FrameDataSource.h"
#include "WCPNav/SimDataSource.h"
#include "WCPNav/SliceDataSource.h"
#include "WCPSst/Util.h"
#include "WCPData/SimTruth.h"
#include "WCP2dToy/ToyDepositor.h"
#include "WCPNav/GenerativeFDS.h"
#include "WCP2dToy/ToySignalSimu.h"
#include "WCP2dToy/ToySignalSimuTrue.h"
#include "WCP2dToy/DataSignalGaus.h"
#include "WCP2dToy/DataSignalWien.h"

#include "TApplication.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TH1F.h"
#include "TFile.h"
#include "TGraph2D.h"
#include "TColor.h"
#include "TVectorD.h"
#include "TMatrixD.h"
#include <iostream>

using namespace WCP;
using namespace std;




/** * Main function to execute the wire-cell-uboone program.
 *
 * Parses command-line arguments to either convert wire numbers to positions or positions to wire numbers,
 * depending on the input parameters provided.
 *
 * @param argc Number of command-line arguments.
 * @param argv Array of command-line argument strings.
 * @return Integer exit status of the program.
  * Initializes the geometry data source from a specified configuration file.
 *
 * Reads the geometry information required for converting between wire numbers and positions.
 *
 * @param filename Path to the ChannelWireGeometry.txt file containing geometry data.
  * Retrieves the extent of the geometry data loaded from the configuration file.
 *
 * Returns the spatial boundaries of the geometry model.
 *
 * @return Vector representing the extent of the geometry.
  * Converts wire indices to a crossing point in space.
 *
 * Given wire indices for one or more planes, calculates the intersection point in Cartesian coordinates.
 *
 * @param wire1 Reference to the first wire object.
 * @param wire2 Reference to the second wire object.
 * @param[out] point Output vector where the calculated intersection point will be stored.
  * Checks whether a given point lies within the YZ plane boundaries of the geometry.
 *
 * Determines if the point is inside the valid region along the Y and Z axes.
 *
 * @param point Point object representing the location to check.
 * @return Boolean indicating whether the point is contained within the YZ boundaries.
  * Finds the closest wire to a given point in a specified plane.
 *
 * Searches among wires in the designated plane to find the one nearest to the provided point.
 *
 * @param point Point object representing the reference location.
 * @param plane_type Type identifier for the wire plane.
 * @return Pointer to the closest GeomWire object.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
int main(int argc, char* argv[])
{
  if (argc < 2) {
    cerr << "usage: wire-cell-uboone /path/to/ChannelWireGeometry.txt -u[u channle #] -v[v channel #] -w[w channel #] -x[position cm] -y[position cm] -z[position cm]" << endl;
    return 1;
  }

  WCPSst::GeomDataSource gds(argv[1]);
  std::vector<double> ex = gds.extent();
  
  int uwire = -1;
  int vwire = -1;
  int wwire = -1;
  double x_pos = 0;
  double y_pos = -100*units::m;
  double z_pos = -100*units::m;

  //  float unit_dis = 1.14753;  // 70 KV @ 226.5 V/cm
  float unit_dis = 1.101;  // 70 KV @ 273 V/cm
  //float unit_dis = 1.6;  // test

  int num_uvw=0;
  int num_xyz=0;
  
  for (Int_t i = 1; i != argc; i++){
    switch(argv[i][1]){
    case 'u':
      uwire = atoi(&argv[i][2]);
      num_uvw++;
      break;
    case 'v':
      vwire = atoi(&argv[i][2])-2400;
      num_uvw++;
      break;
    case 'w':
      wwire = atoi(&argv[i][2])-2400-2400;
      num_uvw++;
      break;
    case 'x':
      x_pos = atof(&argv[i][2])*units::cm; 
      num_xyz ++;
      break;
    case 'y':
      y_pos = atof(&argv[i][2])*units::cm; 
      num_xyz ++;
      break;
    case 'z':
      z_pos = atof(&argv[i][2])*units::cm; 
      num_xyz ++;
      break;
    }
  }

  // x_pos -= 52 * unit_dis/10.*units::cm;

  if (num_uvw  > num_xyz){
    
    // convert wire num into position
    Vector p;
    if (uwire >=0 && vwire >=0){
      const GeomWire *u_wire = gds.by_planeindex(WirePlaneType_t(0),uwire);
      const GeomWire *v_wire = gds.by_planeindex(WirePlaneType_t(1),vwire);
      gds.crossing_point(*u_wire,*v_wire,p);
      
      std::cout << "UV (x,y,z): " << p.x/units::cm << ", " << p.y/units::cm << ", " << p.z/units::cm  << " cm" << std::endl;
    }else if (uwire >=0 && wwire >=0){
      const GeomWire *u_wire = gds.by_planeindex(WirePlaneType_t(0),uwire);
      const GeomWire *w_wire = gds.by_planeindex(WirePlaneType_t(2),wwire);
      gds.crossing_point(*u_wire,*w_wire,p);
      
      std::cout << "UW (x,y,z): " << p.x/units::cm << ", " << p.y/units::cm << ", " << p.z/units::cm  << " cm" << std::endl;
    }else if (vwire >=0 && wwire >=0){
      const GeomWire *w_wire = gds.by_planeindex(WirePlaneType_t(2),wwire);
      const GeomWire *v_wire = gds.by_planeindex(WirePlaneType_t(1),vwire);
      gds.crossing_point(*w_wire,*v_wire,p);
      
      std::cout << "VW (x,y,z): " << p.x/units::cm << ", " << p.y/units::cm << ", " << p.z/units::cm  << " cm" << std::endl;
    }
  }else{

    std::cout << x_pos/units::cm << " " << y_pos/units::cm << " " << z_pos/units::cm << " cm" << std::endl;

    // convert position into wire number
    Point p(x_pos,y_pos,z_pos);
    if (gds.contained_yz(p)){
      const GeomWire *u_wire = gds.closest(p,WirePlaneType_t(0));
      const GeomWire *v_wire = gds.closest(p,WirePlaneType_t(1));
      const GeomWire *w_wire = gds.closest(p,WirePlaneType_t(2));
      std::cout << "U: " << u_wire->index() << std::endl;
      std::cout << "V: " << v_wire->index() + 2400 << std::endl;
      std::cout << "W: " << w_wire->index() + 4800 << std::endl;
      std::cout << "T: " << (x_pos)/(unit_dis*units::mm)*2+3200 << " " << (x_pos)/(unit_dis*units::mm)*2/4.+800 << std::endl;
    }else{
      std::cout << "Point is outside the boundary! " << std::endl;
    }
  }
  

  return 0;
}
