#include "WCPSst/GeomDataSource.h"
#include "WCPSst/DatauBooNEFrameDataSource.h"
#include "WCPSst/ToyuBooNESliceDataSource.h"
#include "WCP2dToy/ToyEventDisplay.h"
#include "WCP2dToy/ToyTiling.h"
#include "WCP2dToy/BadTiling.h"

#include "WCP2dToy/MergeToyTiling.h"
#include "WCP2dToy/TruthToyTiling.h"
#include "WCP2dToy/SimpleBlobToyTiling.h"

#include "WCP2dToy/ToyMatrix.h"
#include "WCP2dToy/ToyMatrixExclusive.h"
#include "WCP2dToy/ToyMatrixKalman.h"
#include "WCP2dToy/ToyMatrixIterate.h"
#include "WCP2dToy/ToyMatrixIterate_SingleWire.h"
#include "WCP2dToy/ToyMatrixIterate_Only.h"


#include "WCP2dToy/ToyMatrixMarkov.h"
#include "WCP2dToy/ToyMetric.h"
#include "WCP2dToy/BlobMetric.h"

#include "WCPData/MergeGeomCell.h"
#include "WCPData/MergeGeomWire.h"

#include "WCPData/GeomCluster.h"
//#include "WCPNav/SliceDataSource.h"


#include "WCPNav/FrameDataSource.h"
#include "WCPNav/SimDataSource.h"
#include "WCPNav/SliceDataSource.h"
#include "WCPSst/Util.h"
#include "WCPData/SimTruth.h"
#include "WCP2dToy/ToyDepositor.h"
#include "WCPNav/GenerativeFDS.h"
#include "WCP2dToy/ToySignalSimu.h"
#include "WCP2dToy/ToySignalSimuTrue.h"
#include "WCP2dToy/DataSignalGaus.h"
#include "WCP2dToy/DataSignalWien.h"

#include "TApplication.h"
#include "TCanvas.h"
#include "TStyle.h"
#include "TH1F.h"
#include "TFile.h"
#include "TGraph2D.h"
#include "TColor.h"
#include "TVectorD.h"
#include "TMatrixD.h"
#include <iostream>

using namespace WCP;
using namespace std;




/**
 * @brief Main program entry point.
 *
 * This function initializes the application, processes command line arguments,
 * sets up the geometry data source, retrieves and prints its extent,
 * and performs further calculations based on the geometry data.
 *
 * @param argc Number of command line arguments.
 * @param argv Array of command line argument strings.
 * @return Exit status of the program.
  
 * @brief Processes command line arguments and checks for sufficient input.
 *
 * Verifies that the number of command line arguments is at least 2.
 * If not, prints an error message with usage instructions and exits.
 
 * @brief Parses command line options and sets corresponding flags.
 *
 * Iterates through command line arguments starting from the second one,
 * identifies option switches, and updates related variable settings.
 
 * @brief Enables or disables two-plane reconstruction based on user input.
 *
 * Checks the value of the two_plane flag set during command line parsing.
 * If enabled, prints a confirmation message.
 
 * @brief Creates a geometry data source instance from a file path.
 *
 * Uses the first command line argument as the path to initialize the geometry data source.
 
 * @brief Retrieves and prints the extent of the geometry data source.
 *
 * Calls the extent method of the geometry data source to get its dimensions,
 * then prints these dimensions in millimeters and meters.
 
 * @brief Prints pitch values for each wire plane type.
 *
 * Retrieves pitch values for each of the three wire plane types (0, 1, 2)
 * using the pitch method of the geometry data source and prints them.
 
 * @brief Prints angle values for each wire plane type.
 *
 * Retrieves angle values for each of the three wire plane types (0, 1, 2)
 * using the angle method of the geometry data source and prints them.
 
 * @brief Calculates and prints lengths of wires in each plane.
 *
 * Iterates over wires in each of the three planes, calculates the length
 * of each wire using its endpoints, and prints the plane number, wire index, and length.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
int main(int argc, char* argv[])
{
  if (argc < 2) {
    cerr << "usage: wire-cell-uboone /path/to/ChannelWireGeometry.txt /path/to/celltree.root eve_num -t[0,1] -s[0,1,2]" << endl;
    return 1;
  }

  int two_plane = 0;
  int save_file = 0;
  int nt_off1 = 0;
  int nt_off2 = 0;
  for(Int_t i = 1; i != argc; i++){
     switch(argv[i][1]){
     case 't':
       two_plane = atoi(&argv[i][2]); 
       break;
     case 's':
       save_file = atoi(&argv[i][2]); 
       break;
     case 'a':
       nt_off1 = atoi(&argv[i][2]);
       break;
     case 'b':
       nt_off2 = atoi(&argv[i][2]);
       break;
     }
  }
  
  if (two_plane)
    cout << "Enable Two Plane Reconstruction " << endl; 
  
  WCPSst::GeomDataSource gds(argv[1]);
  std::vector<double> ex = gds.extent();
  cerr << "Extent: "
       << " x:" << ex[0]/units::mm << " mm"
       << " y:" << ex[1]/units::m << " m"
       << " z:" << ex[2]/units::m << " m"
       << endl;

  cout << "Pitch: " << gds.pitch(WirePlaneType_t(0)) 
       << " " << gds.pitch(WirePlaneType_t(1)) 
       << " " << gds.pitch(WirePlaneType_t(2))
       << endl;
  cout << "Angle: " << gds.angle(WirePlaneType_t(0)) 
       << " " << gds.angle(WirePlaneType_t(1)) 
       << " " << gds.angle(WirePlaneType_t(2))
       << endl;
  
  for (Int_t i=0;i!=gds.wires_in_plane(WirePlaneType_t(0)).size();i++){
    const GeomWire *wire = gds.wires_in_plane(WirePlaneType_t(0)).at(i);
    std::cout << 0 << " " << i << " " << sqrt(pow(wire->point1().y-wire->point2().y,2)
				  + pow(wire->point1().z-wire->point2().z,2))/units::cm
	      << std::endl;
  }

   for (Int_t i=0;i!=gds.wires_in_plane(WirePlaneType_t(1)).size();i++){
    const GeomWire *wire = gds.wires_in_plane(WirePlaneType_t(1)).at(i);
    std::cout << 1 << " " << i << " " << sqrt(pow(wire->point1().y-wire->point2().y,2)
				  + pow(wire->point1().z-wire->point2().z,2))/units::cm
	      << std::endl;
  }

    for (Int_t i=0;i!=gds.wires_in_plane(WirePlaneType_t(2)).size();i++){
    const GeomWire *wire = gds.wires_in_plane(WirePlaneType_t(2)).at(i);
    std::cout << 2 << " " << i << " " << sqrt(pow(wire->point1().y-wire->point2().y,2)
					      + pow(wire->point1().z-wire->point2().z,2))/units::cm
	      << std::endl;
  }


  return 0;
  
} // main()
