#include "WCP2dToy/ExecMon.h"
#include <sstream>

using namespace WCP;

ExecMon::ExecMon(const std::string& msg, TimeKeeper::ptime starting_time)
    : tk(msg, starting_time)
    , mu(msg) { }
    
ExecMon::~ExecMon() { }

/**
 * @brief Formats execution monitoring message including time and memory usage information
 * @param msg Message to be included in the formatted string
 * @param now Current time point
 * @param mumu Memory usage data
 * @return Formatted string containing time and memory usage information
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string ExecMon::operator()(std::string msg, TimeKeeper::ptime now, MemUsage::memusage mumu)
{
    std::stringstream ss;
    ss << "Time: " << tk(msg,now) << "\n"
       << "Memory: " << mu(msg,mumu);
    return ss.str();
}


/**
 * Returns a string containing a time and memory usage summary.
 *
 * @return A formatted string with time and memory usage information.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string ExecMon::summary() const
{
    std::stringstream ss;
    ss << "Time summary:\n" << tk.summary() << "\nMemory usage:\n" << mu.summary();
    return ss.str();
}

