#include "WCP2dToy/MemUsage.h"

#include <unistd.h>
#include <iostream>		// debugging
#include <sstream>

using namespace std;
using namespace WCP;

/**
 * @brief Calculates the resident set size of the process in megabytes.
 *
 * This function reads the resident set size from the /proc/self/statm file,
 * calculates the page size in kilobytes, and returns the product of 
 * the resident set size and page size as the resident set size in megabytes.
 *
 * @return The resident set size of the process in megabytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
static double memusage_linux_resident() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double rss = resident * page_size_kb;
    return rss;
}

/**
 * @brief Calculates the shared memory usage of the current process on Linux systems.
 *
 * This function reads the memory statistics of the current process from the /proc/self/statm file,
 * extracts the total size, resident set size, and shared library size, then calculates the 
 * shared memory usage in kilobytes.
 *
 * @return The shared memory usage of the current process in kilobytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
static double memusage_linux_shared() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double shm = share * page_size_kb;
    return shm;
}

/**
 * @brief Calculates the total memory usage of the current process in megabytes.
 *
 * This function reads the memory statistics from the /proc/self/statm file,
 * extracts the total size and resident set size, and calculates the total memory
 * usage based on the system's page size.
 *
 * @return The total memory usage of the current process in megabytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
static double memusage_linux_size() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double siz = tSize * page_size_kb;
    return siz;
}


/**
 * @brief Returns the resident memory usage.
 *
 * This function returns the amount of memory currently being used by the process,
 * taking into account the operating system's memory management.
 *
 * @return The resident memory usage in bytes, or -1 if not supported.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
double WCP::memusage_resident() {
#ifdef __linux__
    return memusage_linux_resident();
#endif
    return -1;
}

/**
 * @brief Returns the memory usage of the shared memory on Linux systems.
 *
 * @return The memory usage of the shared memory, or -1 if not on a Linux system.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
double WCP::memusage_shared()
{
#ifdef __linux__
    return memusage_linux_shared();
#endif
    return -1;
}
/**
 * @brief Returns the memory usage size.
 *
 * @return The memory usage size if the platform is Linux, otherwise returns -1.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
double WCP::memusage_size()
{
#ifdef __linux__
    return memusage_linux_size();
#endif
    return -1;
}


/**
 * Constructs a MemUsage object with a message.
 *
 * @param msg the message associated with the memory usage
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
MemUsage::MemUsage(const std::string& msg)
{
    push(msg);
}

MemUsage::~MemUsage()
{
}

/**
 * Returns the current memory usage.
 *
 * @return The current memory usage.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
MemUsage::memusage MemUsage::current() const
{
    return memusage(memusage_size(), memusage_resident());
}
/**
 * @brief Adds a memory usage event to the list of tracked events.
 * 
 * @param msg Description of the memory usage event.
 * @param mu Memory usage information, defaults to current usage if negative values are provided.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
void MemUsage::push(const std::string& msg, MemUsage::memusage mu)
{
    if (mu.first < 0 && mu.second < 0) {
	mu = current();
    }
    m_events.push_back(event(mu,msg));
}

/**
 * @brief Overloads operator() to record memory usage information 
 * @param msg message associated with memory usage
 * @param mu type of memory usage
 * @return string representation of memory usage information
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string MemUsage::operator()(std::string msg, MemUsage::memusage mu)
{
    push(msg, mu);
    return emit(-1);
}

	/// Return event by index.
MemUsage::event MemUsage::operator[](int ind) const
{
    while (ind < 0) { ind += m_events.size();}

    return m_events[ind];
}

/**
 * Returns a string summary of memory usage for all events.
 *
 * @return A formatted string containing memory usage information for each event.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string MemUsage::summary() const
{
    stringstream ss;
    for (int ind=0; ind<m_events.size(); ++ind) {
	ss << this->emit(ind) << "\n";
    }
    return ss.str();
}

/**
 * @brief Emits a string representation of memory usage at a given index.
 *
 * This function calculates the difference in memory usage between the current event and the previous event,
 * and returns a formatted string containing the total and incremental memory usage information.
 *
 * @param ind Index of the event for which to emit memory usage information.
 * @return A string representing the memory usage at the specified index.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string MemUsage::emit(int ind) const
{
    while (ind < 0) { ind += m_events.size();}
    int prev_ind = ind-1;
    if (prev_ind<0) prev_ind=0;

    const memusage& prev_mem = (*this)[prev_ind].first;
    const memusage& evt_mem = (*this)[ind].first;
    const string& evt_msg = (*this)[ind].second;

    memusage from_prev(evt_mem.first - prev_mem.first, evt_mem.second - prev_mem.second);

    stringstream ss;
    ss << "MEM: total: size=" << evt_mem.first << "K, res=" << evt_mem.second << "K "
       << "increment: size=" << from_prev.first << "K, res=" << from_prev.second << "K "
       << evt_msg;
    return ss.str();
}
