#include "WCP2dToy/MemUsage.h"

#include <unistd.h>
#include <iostream>		// debugging
#include <sstream>

using namespace std;
using namespace WCP;

/** * @brief Retrieves the resident set size (RSS) memory usage of the current process on Linux.
 *
 * This function reads the `/proc/self/statm` file to obtain memory statistics,
 * calculates the RSS in kilobytes, and returns it.
 *
 * @return The resident set size of the process in kilobytes.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
static double memusage_linux_resident() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double rss = resident * page_size_kb;
    return rss;
}

/** * @brief Retrieves the amount of shared memory usage by the current process on Linux.
 *
 * This function reads the `/proc/self/statm` file to obtain memory statistics,
 * specifically focusing on the shared memory size. It calculates the shared memory
 * usage by multiplying the shared pages count by the system's page size, converting
 * the result to kilobytes.
 *
 * @return The amount of shared memory used by the process in kilobytes.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
static double memusage_linux_shared() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double shm = share * page_size_kb;
    return shm;
}

/** * @brief Retrieves the total virtual memory usage of the current process on Linux.
 *
 * This function reads the `/proc/self/statm` file to obtain the size of the process's virtual memory,
 * then multiplies it by the system's page size to convert it to kilobytes.
 *
 * @return Total virtual memory usage in kilobytes.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
static double memusage_linux_size() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double siz = tSize * page_size_kb;
    return siz;
}


/** * @brief Retrieves the resident memory usage of the process.
 *
 * This function returns the amount of physical memory used by the calling process,
 * measured in kilobytes. It utilizes platform-specific methods to gather this information.
 *
 * On Linux platforms, the function delegates the task to `memusage_linux_resident`.
 * If the platform is not supported, it returns -1.
 *
 * @return double The resident memory usage in kilobytes, or -1 if unsupported.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
double WCP::memusage_resident() {
#ifdef __linux__
    return memusage_linux_resident();
#endif
    return -1;
}

/** * @brief Retrieves the amount of shared memory usage on Linux systems.
 *
 * This function returns the amount of shared memory used by the process on Linux platforms.
 * If called on a non-Linux platform, it returns -1 indicating unsupported functionality.
 *
 * @return double Amount of shared memory used in bytes if on Linux, otherwise -1.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
double WCP::memusage_shared()
{
#ifdef __linux__
    return memusage_linux_shared();
#endif
    return -1;
}
/** * @brief Retrieves the size of memory usage on Linux systems.
 *
 * This function returns the memory usage size if the operating system is Linux,
 * otherwise it returns -1 indicating unsupported OS.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
double WCP::memusage_size()
{
#ifdef __linux__
    return memusage_linux_size();
#endif
    return -1;
}


/** * @brief Constructor for MemUsage class initializing with a message.
 *
 * @param msg Initial message to store in the memory usage log.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
MemUsage::MemUsage(const std::string& msg)
{
    push(msg);
}

MemUsage::~MemUsage()
{
}

/** * @brief Retrieves the current memory usage statistics.
 *
 * This method calculates and returns the current memory usage details,
 * including both the total allocated size and the resident set size.
 *
 * @return A memusage object containing the current memory usage statistics.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
MemUsage::memusage MemUsage::current() const
{
    return memusage(memusage_size(), memusage_resident());
}
/** * @brief Pushes a memory usage event with a message and memory usage details.
 *
 * If the provided memory usage values are negative, it retrieves the current memory usage before storing the event.
 *
 * @param msg Description associated with the memory usage event.
 * @param mu Pair containing virtual and resident memory usage values.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
void MemUsage::push(const std::string& msg, MemUsage::memusage mu)
{
    if (mu.first < 0 && mu.second < 0) {
	mu = current();
    }
    m_events.push_back(event(mu,msg));
}

/** * @brief Pushes a message along with its associated memory usage information onto the internal stack and returns a formatted string representing the current memory usage statistics.
 *
 * @param msg The message to associate with the memory usage snapshot.
 * @param mu Memory usage details encapsulated in a memusage struct.
 * @return A string containing the formatted memory usage statistics.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
std::string MemUsage::operator()(std::string msg, MemUsage::memusage mu)
{
    push(msg, mu);
    return emit(-1);
}

	/// Return event by index.
MemUsage::event MemUsage::operator[](int ind) const
{
    while (ind < 0) { ind += m_events.size();}

    return m_events[ind];
}

/** * @brief Generates a summary of memory usage events.
 *
 * Iterates through the stored memory usage events and appends the result of emit method for each event to a string stream.
 * Returns the concatenated string representing the summary of all memory usage events.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
std::string MemUsage::summary() const
{
    stringstream ss;
    for (int ind=0; ind<m_events.size(); ++ind) {
	ss << this->emit(ind) << "\n";
    }
    return ss.str();
}

/** * Emits a formatted string representing memory usage information for a specified event index.
 *
 * @param ind Index of the event for which memory usage details are emitted.
 * @return Formatted string containing memory usage statistics including total and incremental sizes and resident sets, along with any associated message.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
std::string MemUsage::emit(int ind) const
{
    while (ind < 0) { ind += m_events.size();}
    int prev_ind = ind-1;
    if (prev_ind<0) prev_ind=0;

    const memusage& prev_mem = (*this)[prev_ind].first;
    const memusage& evt_mem = (*this)[ind].first;
    const string& evt_msg = (*this)[ind].second;

    memusage from_prev(evt_mem.first - prev_mem.first, evt_mem.second - prev_mem.second);

    stringstream ss;
    ss << "MEM: total: size=" << evt_mem.first << "K, res=" << evt_mem.second << "K "
       << "increment: size=" << from_prev.first << "K, res=" << from_prev.second << "K "
       << evt_msg;
    return ss.str();
}
