#include "WCP2dToy/MemUsage.h"

#include <unistd.h>
#include <iostream>		// debugging
#include <sstream>

using namespace std;
using namespace WCP;

/**
 * Calculates the resident set size of the process memory usage on Linux systems.
 *
 * @return The resident set size of the process memory usage in kilobytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
static double memusage_linux_resident() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double rss = resident * page_size_kb;
    return rss;
}

/**
 * Calculates the shared memory usage of the current process on Linux systems.
 *
 * @return The amount of shared memory used by the process in kilobytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
static double memusage_linux_shared() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double shm = share * page_size_kb;
    return shm;
}

/**
 * @brief Calculates the total memory usage of the process in megabytes.
 *
 * @return The total memory usage of the process in megabytes.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
static double memusage_linux_size() {
    int tSize = 0, resident = 0, share = 0;
    ifstream buffer("/proc/self/statm");
    buffer >> tSize >> resident >> share;
    buffer.close();

    long page_size_kb = sysconf(_SC_PAGE_SIZE) / 1024; // in case x86-64 is configured to use 2MB pages
    double siz = tSize * page_size_kb;
    return siz;
}


/**
 * Returns the resident memory usage of the process.
 *
 * @return The resident memory usage in bytes or -1 if unsupported.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
double WCP::memusage_resident() {
#ifdef __linux__
    return memusage_linux_resident();
#endif
    return -1;
}

/**
 * Returns the memory usage of shared resources.
 *
 * @return Memory usage value or negative value if unsupported
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
double WCP::memusage_shared()
{
#ifdef __linux__
    return memusage_linux_shared();
#endif
    return -1;
}
/**
 * Returns the memory usage size.
 *
 * @return Memory usage size if supported, -1 otherwise.* This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
double WCP::memusage_size()
{
#ifdef __linux__
    return memusage_linux_size();
#endif
    return -1;
}


/**
 * Constructor for MemUsage object initializing memory usage tracking with message.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
MemUsage::MemUsage(const std::string& msg)
{
    push(msg);
}

MemUsage::~MemUsage()
{
}

/**
 * Returns the current memory usage of the system.
 *
 * @return The current memory usage.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
MemUsage::memusage MemUsage::current() const
{
    return memusage(memusage_size(), memusage_resident());
}
/**
 * Adds a new event to the memory usage log with the specified message and memory usage details.
 *
 * @param msg   Message associated with the event.
 * @param mu    Memory usage details.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
void MemUsage::push(const std::string& msg, MemUsage::memusage mu)
{
    if (mu.first < 0 && mu.second < 0) {
	mu = current();
    }
    m_events.push_back(event(mu,msg));
}

/**
 * @brief Returns memory usage information as a string after pushing message and memory usage data.
 *
 * @param msg Message associated with memory usage data.
 * @param mu Memory usage data to be pushed.
 * @return String representation of memory usage information.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string MemUsage::operator()(std::string msg, MemUsage::memusage mu)
{
    push(msg, mu);
    return emit(-1);
}

	/// Return event by index.
MemUsage::event MemUsage::operator[](int ind) const
{
    while (ind < 0) { ind += m_events.size();}

    return m_events[ind];
}

/**
 * Returns a string summary of memory usage events
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string MemUsage::summary() const
{
    stringstream ss;
    for (int ind=0; ind<m_events.size(); ++ind) {
	ss << this->emit(ind) << "\n";
    }
    return ss.str();
}

/**
 * Returns a formatted string describing memory usage at a specified index.
 *
 * @param ind Index of the memory event to emit.
 * @return A string containing memory usage information.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.01.
*/ 
std::string MemUsage::emit(int ind) const
{
    while (ind < 0) { ind += m_events.size();}
    int prev_ind = ind-1;
    if (prev_ind<0) prev_ind=0;

    const memusage& prev_mem = (*this)[prev_ind].first;
    const memusage& evt_mem = (*this)[ind].first;
    const string& evt_msg = (*this)[ind].second;

    memusage from_prev(evt_mem.first - prev_mem.first, evt_mem.second - prev_mem.second);

    stringstream ss;
    ss << "MEM: total: size=" << evt_mem.first << "K, res=" << evt_mem.second << "K "
       << "increment: size=" << from_prev.first << "K, res=" << from_prev.second << "K "
       << evt_msg;
    return ss.str();
}
