#include "WCP2dToy/pd_Data_FDS.h"

using namespace WCP;

/** * @brief Constructor for pdDataFDS class initializing geometric data source and deconvolution histograms.
 *
 * Initializes the geometry data source and processes deconvolution histograms for U, V, and W planes.
 * Extracts wire selections for each plane, sets up traces for each channel, and populates charge values from histograms.
 *
 * @param gds Geometry data source containing information about wire planes.
 * @param hu_decon Pointer to histogram representing deconvolved charges for U plane.
 * @param hv_decon Pointer to histogram representing deconvolved charges for V plane.
 * @param hw_decon Pointer to histogram representing deconvolved charges for W plane.
 * @param eve_num Event number associated with the data frame.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
WCP2dToy::pdDataFDS::pdDataFDS(const WCP::GeomDataSource& gds, TH2I *hu_decon, TH2I *hv_decon, TH2I *hw_decon, int eve_num)
  : gds(gds)
{
  GeomWireSelection wires_u = gds.wires_in_plane(WirePlaneType_t(0));
  GeomWireSelection wires_v = gds.wires_in_plane(WirePlaneType_t(1));
  GeomWireSelection wires_w = gds.wires_in_plane(WirePlaneType_t(2));

  nwire_u = wires_u.size();
  nwire_v = wires_v.size();
  nwire_w = wires_w.size();

  
  
  frame.clear();		// win or lose, we start anew

  frame.index =eve_num;
  bins_per_frame = hu_decon->GetNbinsY();
  // U plane
  for (size_t ind=0; ind < hu_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hu_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }
  
  // V plane
  for (size_t ind=0; ind < hv_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind + nwire_u;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hv_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }

  // W plane
  for (size_t ind=0; ind < hw_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind + nwire_u + nwire_v;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hw_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }

  //std::cout << frame.traces.size() << " " << bins_per_frame << std::endl;
}



/** * @brief Constructor for pdDataFDS class initializing geometric data source and charge traces from histogram data.
 *
 * @param gds Reference to the geometry data source containing wire information.
 * @param hu_decon Pointer to the TH2F histogram representing deconvolved charges in the U plane.
 * @param hv_decon Pointer to the TH2F histogram representing deconvolved charges in the V plane.
 * @param hw_decon Pointer to the TH2F histogram representing deconvolved charges in the W plane.
 * @param eve_num Event number associated with the data frame.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
WCP2dToy::pdDataFDS::pdDataFDS(const WCP::GeomDataSource& gds, TH2F *hu_decon, TH2F *hv_decon, TH2F *hw_decon, int eve_num)
  : gds(gds)
{
  GeomWireSelection wires_u = gds.wires_in_plane(WirePlaneType_t(0));
  GeomWireSelection wires_v = gds.wires_in_plane(WirePlaneType_t(1));
  GeomWireSelection wires_w = gds.wires_in_plane(WirePlaneType_t(2));

  nwire_u = wires_u.size();
  nwire_v = wires_v.size();
  nwire_w = wires_w.size();

  
  
  frame.clear();		// win or lose, we start anew

  frame.index =eve_num;
  bins_per_frame = hu_decon->GetNbinsY();
  // U plane
  for (size_t ind=0; ind < hu_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hu_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }
  
  // V plane
  for (size_t ind=0; ind < hv_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind + nwire_u;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hv_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }

  // W plane
  for (size_t ind=0; ind < hw_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind + nwire_u + nwire_v;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hw_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }

  //std::cout << frame.traces.size() << " " << bins_per_frame << std::endl;
}

/** * @brief Refreshes the frame data structure with charge information from three histogram objects representing different planes (U, V, W).
 *
 * This method initializes the frame by clearing any previous data and setting its index to the current event number.
 * It then populates the frame's traces vector with charge data extracted from the input histograms.
 * Each trace corresponds to a channel in one of the three planes, and contains the charge values across multiple time bins.
 *
 * @param hu_decon Pointer to the histogram object containing deconvolved charge data for the U plane.
 * @param hv_decon Pointer to the histogram object containing deconvolved charge data for the V plane.
 * @param hw_decon Pointer to the histogram object containing deconvolved charge data for the W plane.
 * @param eve_num Event number associated with the current frame.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
void WCP2dToy::pdDataFDS::refresh(TH2F *hu_decon, TH2F *hv_decon, TH2F *hw_decon, int eve_num){
    
  frame.clear();		// win or lose, we start anew

  frame.index =eve_num;
  bins_per_frame = hu_decon->GetNbinsY();
  // U plane
  for (size_t ind=0; ind < hu_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hu_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }
  
  // V plane
  for (size_t ind=0; ind < hv_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind + nwire_u;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hv_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }

  // W plane
  for (size_t ind=0; ind < hw_decon->GetNbinsX(); ++ind) {
    WCP::Trace trace;
    trace.chid = ind + nwire_u + nwire_v;
    trace.tbin = 0;		// full readout, if zero suppress this would be non-zero
    trace.charge.resize(bins_per_frame, 0.0);
    
    for (int ibin=0; ibin != bins_per_frame; ibin++) {
      trace.charge.at(ibin) = hw_decon->GetBinContent(ind+1,ibin+1);
    }
    frame.traces.push_back(trace);
  }
}


WCP2dToy::pdDataFDS::~pdDataFDS(){
}

int WCP2dToy::pdDataFDS::jump(int frame_number){
  return frame.index;
}

int WCP2dToy::pdDataFDS::size() const{
  return 1;
}
