#include "WCP2dToy/TimeKeeper.h"

#include <sstream>
#include <iostream>		// debugging

using namespace std;
using namespace WCP;

/**
 * Constructor initializing time keeper with message and start time
 * @param msg descriptive message for event
 * @param starting_time initial time of event
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
TimeKeeper::TimeKeeper(const std::string& msg, ptime starting_time)
{
    //cerr << "TimeKeeper starting with \"" << msg << "\"" << endl;
    m_events.push_back(event(starting_time, msg));
}

TimeKeeper::~TimeKeeper()
{
}

/**
 * @brief Processes a message and records the current time
 * @param msg Message to be processed
 * @param now Current time
 * @return Result of processing the message
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
std::string TimeKeeper::operator()(std::string msg, ptime now)
{
    //cerr << "TimeKeeper: accepting message: " << msg << endl;
    m_events.push_back(event(now, msg));
    return emit(-1);
}

/**
 * Returns the start time of the TimeKeeper object.
 *
 * @return The start time as a boostposix_timeptime object.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
boost::posix_time::ptime TimeKeeper::start_time() const
{
    return (*this)[0].first;
}
/**
 * Returns the last time kept by the TimeKeeper object.
 *
 * @return The most recent time stored in the TimeKeeper.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
boost::posix_time::ptime TimeKeeper::last_time() const
{
    return (*this)[-1].first;
}
/**
 * Returns the time difference between the last two recorded durations.
 *
 * @return The time difference between the last two recorded durations.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
TimeKeeper::deltat TimeKeeper::last_duration() const
{
    return (*this)[-1].first - (*this)[-2].first;
}

/**
 * Returns the time duration since the start time.
 *
 * @return Time duration since the start time.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
boost::posix_time::time_duration TimeKeeper::since(ptime now) const
{
    return now - start_time();
}

/**
 * Returns the event at the specified index, handling negative indices by wrapping around to the end of the list.
 *
 * @param ind the index of the event to retrieve
 * @return the event at the specified index
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
TimeKeeper::event TimeKeeper::operator[](int ind) const
{
    while (ind < 0) { ind += m_events.size();}

    return m_events[ind];
}

/**
 * Returns a summary string containing emitted events.
 *
 * @return A string representation of all emitted events.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
std::string TimeKeeper::summary() const
{
    stringstream ss;
    for (int ind=0; ind<m_events.size(); ++ind) {
	ss << this->emit(ind) << "\n";
    }
    return ss.str();
}

/**
 * Returns a string representation of an event at the specified index,
 * including the total time elapsed since the start and the time elapsed
 * since the previous event.
 *
 * @param ind the index of the event to retrieve
 * @return a string containing the event details
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
std::string TimeKeeper::emit(int ind) const
{
    while (ind < 0) { ind += m_events.size();}
    //cerr << "emit " << ind << endl;
    int prev_ind = ind-1;
    if (prev_ind<0) prev_ind=0;
    const event& prev = (*this)[prev_ind];
    const event& evt = (*this)[ind];

    deltat from_start = since(evt.first);
    deltat from_last = evt.first - prev.first;

    stringstream ss;
    ss << "TICK: " << from_start.total_milliseconds() << " ms "
       << "(this: " << from_last.total_milliseconds() << " ms) "
       << evt.second;
    return ss.str();
}
