#include "WCP2dToy/TimeKeeper.h"

#include <sstream>
#include <iostream>		// debugging

using namespace std;
using namespace WCP;

/** * @brief Constructs a new TimeKeeper object initialized with a start message and timestamp.
 *
 * @param msg The initial event message describing the start.
 * @param starting_time The timestamp marking the beginning of the timing events.
 <|eot_id|>* This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
TimeKeeper::TimeKeeper(const std::string& msg, ptime starting_time)
{
    //cerr << "TimeKeeper starting with \"" << msg << "\"" << endl;
    m_events.push_back(event(starting_time, msg));
}

TimeKeeper::~TimeKeeper()
{
}

/** * @brief Accepts a timestamped message and stores it internally.
 *
 * This operator overload method takes a string message and a current timestamp,
 * creates an event with these details, and appends it to the internal events list.
 * After storing the event, it returns the result of calling `emit` with -1.
 *
 * @param msg The message associated with the event.
 * @param now The current timestamp.
 * @return The result of the emit call with argument -1.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
std::string TimeKeeper::operator()(std::string msg, ptime now)
{
    //cerr << "TimeKeeper: accepting message: " << msg << endl;
    m_events.push_back(event(now, msg));
    return emit(-1);
}

/** * @brief Retrieves the start time recorded by the TimeKeeper instance.
 *
 * @return boost::posix_time::ptime The earliest timestamp stored in the TimeKeeper.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
boost::posix_time::ptime TimeKeeper::start_time() const
{
    return (*this)[0].first;
}
/** * @brief Retrieves the last recorded timestamp.
 *
 * Returns the most recent timestamp stored in the TimeKeeper instance.
 *
 * @return boost::posix_time::ptime The last recorded timestamp.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
boost::posix_time::ptime TimeKeeper::last_time() const
{
    return (*this)[-1].first;
}
/** * @brief Returns the duration between the last two recorded timestamps.
 *
 * Calculates the difference between the timestamp of the last entry and the second-to-last entry in the TimeKeeper object.
 *
 * @return TimeKeeper::deltat Duration between the last two timestamps.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
TimeKeeper::deltat TimeKeeper::last_duration() const
{
    return (*this)[-1].first - (*this)[-2].first;
}

/** * @brief Calculates the duration since the recorded start time.
 *
 * This method computes the difference between the current point in time (`now`) and the stored `start_time`.
 *
 * @param now Current point in time.
 * @return Duration elapsed since the start time.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
boost::posix_time::time_duration TimeKeeper::since(ptime now) const
{
    return now - start_time();
}

/** * @brief Returns the event at the specified index, wrapping around negative indices.
 *
 * @param ind Index of the event to retrieve. Negative indices wrap around to positive indices.
 * @return Event at the specified index.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
TimeKeeper::event TimeKeeper::operator[](int ind) const
{
    while (ind < 0) { ind += m_events.size();}

    return m_events[ind];
}

/** * Generates a summary of recorded events by emitting details of each event.
 *
 * Iterates through the list of stored events, invoking the emit method for each,
 * appending the resulting string representation to a stringstream. Returns the concatenated
 * string containing summaries of all events.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
std::string TimeKeeper::summary() const
{
    stringstream ss;
    for (int ind=0; ind<m_events.size(); ++ind) {
	ss << this->emit(ind) << "\n";
    }
    return ss.str();
}

/** * Emits a formatted string representing the timing information of an event relative to the start and previous events.
 *
 * @param ind Index of the event to emit timing information for.
 * @return String containing the timing details including milliseconds from start and last event along with event description.
 * This comment was generated by Qwen/Qwen2.5-Coder-32B-Instruct:None at temperature 0.2.
*/ 
std::string TimeKeeper::emit(int ind) const
{
    while (ind < 0) { ind += m_events.size();}
    //cerr << "emit " << ind << endl;
    int prev_ind = ind-1;
    if (prev_ind<0) prev_ind=0;
    const event& prev = (*this)[prev_ind];
    const event& evt = (*this)[ind];

    deltat from_start = since(evt.first);
    deltat from_last = evt.first - prev.first;

    stringstream ss;
    ss << "TICK: " << from_start.total_milliseconds() << " ms "
       << "(this: " << from_last.total_milliseconds() << " ms) "
       << evt.second;
    return ss.str();
}
