#include "WCP2dToy/WCPHolder.h"

using namespace WCP;

/**
 * Constructor initializes holder variables to default values.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
WCP2dToy::WCPHolder::WCPHolder(){
  ncell = 0;
  nwire = 0;

  cell_no = 0;
  wire_no = 0;
}

/**
 * Destructor for WCPHolder class, releases dynamically allocated memory for wires and cells.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
WCP2dToy::WCPHolder::~WCPHolder(){
  for (int i=0;i!=wires.size();i++){
    delete wires.at(i);
  }
  wires.clear();
  for (int i=0;i!=cells.size();i++){
    delete cells.at(i);
  }
  cells.clear();
}


/**
 * Clears the contents of the cell holder by deleting each cell and resetting the container.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void WCP2dToy::WCPHolder::clear_cell(){
  for (int i=0;i!=cells.size();i++){
    delete cells.at(i);
  }
  cells.clear();
}

/**
 * Clears the wire holder by deleting all stored wires and resetting the container.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void WCP2dToy::WCPHolder::clear_wire(){
  for (int i=0;i!=wires.size();i++){
    delete wires.at(i);
  }
  wires.clear();
}

/**
 * Adds a geometric wire to the holder.
 *
 * @param wire pointer to the GeomWire object to be added
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void WCP2dToy::WCPHolder::AddWire(GeomWire *wire){
  nwire++;
  wires.push_back(wire);
}

/**
 * Increments the cell count and appends a new geometric cell to the collection. 
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.2.
*/ 
void WCP2dToy::WCPHolder::AddCell(GeomCell *cell){
  ncell++;
  cells.push_back(cell);
}
