#include "WCP2dToy/WCPHolder.h"

using namespace WCP;

/**
 * Constructor for initializing holder object with default values.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
WCP2dToy::WCPHolder::WCPHolder(){
  ncell = 0;
  nwire = 0;

  cell_no = 0;
  wire_no = 0;
}

/**
 * @brief Destructor for WCPHolder class
 * 
 * @details Releases dynamically allocated memory for wires and cells
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
WCP2dToy::WCPHolder::~WCPHolder(){
  for (int i=0;i!=wires.size();i++){
    delete wires.at(i);
  }
  wires.clear();
  for (int i=0;i!=cells.size();i++){
    delete cells.at(i);
  }
  cells.clear();
}


/**
 * Clears the cell container by deleting all stored cell objects and resetting the container.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void WCP2dToy::WCPHolder::clear_cell(){
  for (int i=0;i!=cells.size();i++){
    delete cells.at(i);
  }
  cells.clear();
}

/**
 * Clears the collection of wires by deleting each wire object and removing all elements from the container.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void WCP2dToy::WCPHolder::clear_wire(){
  for (int i=0;i!=wires.size();i++){
    delete wires.at(i);
  }
  wires.clear();
}

/**
 * @brief Adds a wire to the holder.
 * 
 * Increments the wire count and appends the wire to the list of wires.
 * 
 * @param wire The wire to be added to the holder.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void WCP2dToy::WCPHolder::AddWire(GeomWire *wire){
  nwire++;
  wires.push_back(wire);
}

/**
 * Adds a cell to the holder.
 *
 * @param cell The cell to be added.
 * This comment was generated by meta-llama/Llama-3.3-70B-Instruct:None at temperature 0.5.
*/ 
void WCP2dToy::WCPHolder::AddCell(GeomCell *cell){
  ncell++;
  cells.push_back(cell);
}
